"""Symbol retrieval public facade.

Generated by Pass 050F.
"""

from __future__ import annotations

from .symbol_retrieval_evidence_private_impl import _build_symbol_evidence_impl
from .symbol_retrieval_retrieve_private_impl import _retrieve_symbols_impl

__all__ = [
    "build_symbol_evidence",
    "retrieve_symbols",
]


def build_symbol_evidence(*args, **kwargs):
    """Return symbol evidence using the private implementation."""
    return _build_symbol_evidence_impl(*args, **kwargs)


def retrieve_symbols(*args, **kwargs):
    """Retrieve symbol evidence using the private implementation."""
    return _retrieve_symbols_impl(*args, **kwargs)
