"""Private build_symbol_evidence implementation for symbol retrieval.

Generated by Pass 050F.
"""

from __future__ import annotations

import re
from kanda_reasoner_app.project_reasoner_v10.v10_models import SymbolEvidenceItem
from kanda_reasoner_app.project_reasoner_v10.reasoner_retriever_help.query_intents import (
    detect_query_intents,
    is_runtime_heavy_question,
)
from kanda_reasoner_app.project_reasoner_v10.reasoner_retriever_help.query_text import (
    file_name_from_path,
    is_allowed_project_path,
    is_auxiliary_ui_path,
    norm_text,
    tokenize_query,
)


__all__ = []

def _build_symbol_evidence_impl(retriever, symbol_name: str) -> str:
    detail = retriever.idx.symbol_details[symbol_name]
    path = detail['file']
    line = detail['line']
    kind = detail['kind']
    record = detail['record']
    lines: list[str] = []
    lines.append('Symbol: ' + symbol_name)
    lines.append('Kind: ' + kind)
    lines.append('Location: ' + path + ':' + str(line))
    if record.get('docstring'):
        docstring = re.sub('\\s+', ' ', str(record.get('docstring', '')).strip())
        lines.append('Docstring: ' + docstring[:500])
    if kind in ('function', 'method'):
        calls = [c.get('call_name', '') for c in record.get('calls', [])[:20]]
        if calls:
            lines.append('Calls: ' + ' | '.join(calls))
    return '\n'.join(lines)
