"""Architecture test-protection import links for public contract modules.

Imports stay under TYPE_CHECKING so architecture validation can see direct
public-contract links without importing GUI/runtime-heavy modules at runtime.
This file is intentionally declarative: it protects public owners from
unreviewed API drift without exercising side-effect-heavy runtime paths.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import kanda_reasoner_app.backend_payloads.loader
    import kanda_reasoner_app.collector_persistence_io
    import kanda_reasoner_app.engineering_safety.crash_triage
    import kanda_reasoner_app.engineering_safety.project_symbol_atlas_integration
    import kanda_reasoner_app.engineering_safety.refactor_playbook
    import kanda_reasoner_app.engineering_safety.report_writer
    import kanda_reasoner_app.engineering_safety.risk_radar
    import kanda_reasoner_app.engineering_safety.schemas
    import kanda_reasoner_app.error_memory.exporter
    import kanda_reasoner_app.error_memory.fingerprint
    import kanda_reasoner_app.error_memory.heuristic_normalizer
    import kanda_reasoner_app.error_memory.importer
    import kanda_reasoner_app.error_memory.intake
    import kanda_reasoner_app.error_memory.models
    import kanda_reasoner_app.error_memory.paths
    import kanda_reasoner_app.error_memory.scrubber
    import kanda_reasoner_app.error_memory.store
    import kanda_reasoner_app.error_memory_gui.error_memory_tab
    import kanda_reasoner_app.freeze_after_update.blueprint_adapter
    import kanda_reasoner_app.freeze_after_update.contract
    import kanda_reasoner_app.freeze_after_update.freeze_state
    import kanda_reasoner_app.freeze_after_update.paths
    import kanda_reasoner_app.freeze_after_update.send_pack_builder
    import kanda_reasoner_app.freeze_after_update.templates
    import kanda_reasoner_app.freeze_after_update_gui.freeze_after_update_tab
    import kanda_reasoner_app.freeze_hint_intake.contract
    import kanda_reasoner_app.generated_artifact_hygiene
    import kanda_reasoner_app.governance_automation.on_every_push_validator
    import kanda_reasoner_app.governance_automation.release_notes_generator
    import kanda_reasoner_app.insert_missing_docstrings_gui.ai_docstring_generator
    import kanda_reasoner_app.insert_missing_docstrings_gui.ai_docstring_generator_help.models
    import kanda_reasoner_app.insert_missing_docstrings_gui.context_builder
    import kanda_reasoner_app.insert_missing_docstrings_gui.docstring_validator
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.ai_settings
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.constants
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.dialogs
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.layout_builder
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_ai
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_batch
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_editor
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_export
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_heuristic
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_preview
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_docstring_review_support
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.manual_review_boundary_note
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.preferences
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.report_review_panel
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.run_controls
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.scope_controls
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.tab1_audit_docstring_source
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.tab1_audit_write_contracts
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.window_state
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_gui_help.worker_thread
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.ast_safety
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.cli
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.diff_output
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.file_processing
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.heuristic_docstrings
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.insertion_collector
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.insertion_formatting
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.project_exclusion_rules
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.reporting
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.run_orchestrator
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.source_io
    import kanda_reasoner_app.insert_missing_docstrings_gui.insert_missing_docstrings_help.symbol_naming
    import kanda_reasoner_app.insert_missing_docstrings_gui.parallel_runner
    import kanda_reasoner_app.json_splitter.json_splitter_8
    import kanda_reasoner_app.json_splitter.json_splitter_chunk_balancing
    import kanda_reasoner_app.json_splitter.json_splitter_split_reassemble_validation
    import kanda_reasoner_app.json_splitter.json_splitter_split_reassemble_validation_help.core
    import kanda_reasoner_app.json_splitter.json_splitter_web_ai_route_manifest
    import kanda_reasoner_app.live_source_verification.verifier
    import kanda_reasoner_app.local_ai_json_contract
    import kanda_reasoner_app.local_ai_json_enrichment.enrichment_writer
    import kanda_reasoner_app.manage_architecture.ai_review.adapter
    import kanda_reasoner_app.manage_architecture.ai_review.controller
    import kanda_reasoner_app.manage_architecture.ai_review.formatter
    import kanda_reasoner_app.manage_architecture.ai_review.gui_integration
    import kanda_reasoner_app.manage_architecture.ai_review.models
    import kanda_reasoner_app.manage_architecture.ai_review.qt_worker
    import kanda_reasoner_app.manage_architecture.ai_review.review_message_builder
    import kanda_reasoner_app.manage_architecture.ai_review.running_indicator
    import kanda_reasoner_app.manage_architecture.manage_architecture_gui
    import kanda_reasoner_app.manage_architecture.manage_architecture_gui_help.mode_options_hlp
    import kanda_reasoner_app.manage_workflows.ai_review.adapter
    import kanda_reasoner_app.manage_workflows.ai_review.controller
    import kanda_reasoner_app.manage_workflows.ai_review.formatter
    import kanda_reasoner_app.manage_workflows.ai_review.gui_integration
    import kanda_reasoner_app.manage_workflows.ai_review.models
    import kanda_reasoner_app.manage_workflows.ai_review.qt_worker
    import kanda_reasoner_app.manage_workflows.ai_review.review_message_builder
    import kanda_reasoner_app.manage_workflows.ai_review.running_indicator
    import kanda_reasoner_app.manage_workflows.manage_workflows
    import kanda_reasoner_app.manage_workflows.manage_workflows_gui
    import kanda_reasoner_app.manage_workflows.manage_workflows_gui_help.workflow_gui_history
    import kanda_reasoner_app.manage_workflows.manage_workflows_gui_help.workflow_gui_window
    import kanda_reasoner_app.manage_workflows.manage_workflows_gui_help.workflow_gui_worker
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_artifact_route_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_cli
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_command_runner
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_cross_project_generalization_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_detector_context
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_detector_registry
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_documentation_drift_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_environment_contract_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_evidence_output_route_guard_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_file_contract
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_generation
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_history
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_idempotency_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_import_checks
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_interaction_contract_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_issue_models
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_models
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_output_contract
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_project_scan
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_reader_ai_contract_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_reporting
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_rollback_fail_safe_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_step_order_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_step_target_detectors
    import kanda_reasoner_app.manage_workflows.manage_workflows_help.workflow_validation_reference_detectors
    import kanda_reasoner_app.package_migration.package_inventory
    import kanda_reasoner_app.patch_governance.models
    import kanda_reasoner_app.patch_governance.validator
    import kanda_reasoner_app.project_analysis_evidence_paths
    import kanda_reasoner_app.project_exclusion_policy
    import kanda_reasoner_app.project_intelligence.base_engine
    import kanda_reasoner_app.project_intelligence.models
    import kanda_reasoner_app.project_intelligence.report_formatter
    import kanda_reasoner_app.project_intelligence.risk_radar
    import kanda_reasoner_app.project_json_scope_filter
    import kanda_reasoner_app.project_root_resolver
    import kanda_reasoner_app.prompt_library_gui.group_catalog
    import kanda_reasoner_app.prompt_library_gui.library_catalog
    import kanda_reasoner_app.prompt_library_gui.library_paths
    import kanda_reasoner_app.prompt_library_gui.prompt_library_tab
    import kanda_reasoner_app.prompt_router_reasoner_gui.prompt_router_reasoner_tab
    import kanda_reasoner_app.reasoner_context_bundle.active_snapshot_builder
    import kanda_reasoner_app.reasoner_context_bundle.ai_briefing_builder
    import kanda_reasoner_app.reasoner_context_bundle.bundle_checker
    import kanda_reasoner_app.reasoner_context_bundle.bundle_manifest_builder
    import kanda_reasoner_app.reasoner_context_bundle.bundle_orchestrator
    import kanda_reasoner_app.reasoner_context_bundle.bundle_zipper
    import kanda_reasoner_app.reasoner_context_bundle.cli
    import kanda_reasoner_app.reasoner_context_bundle.exclusion_engine
    import kanda_reasoner_app.reasoner_context_bundle.exclusion_provider
    import kanda_reasoner_app.reasoner_context_bundle.exclusion_rules_exporter
    import kanda_reasoner_app.reasoner_context_bundle.file_manifest_builder
    import kanda_reasoner_app.reasoner_context_bundle.handoff_zip_exporter
    import kanda_reasoner_app.reasoner_context_bundle.handoff_zip_exporter_support
    import kanda_reasoner_app.reasoner_context_bundle.handoff_zip_exporter_writer
    import kanda_reasoner_app.reasoner_context_bundle.hashing
    import kanda_reasoner_app.reasoner_context_bundle.json_writer
    import kanda_reasoner_app.reasoner_context_bundle.output_paths
    import kanda_reasoner_app.reasoner_context_bundle.patch_safety_routes_builder
    import kanda_reasoner_app.reasoner_context_bundle.path_normalization
    import kanda_reasoner_app.reasoner_context_bundle.project_context
    import kanda_reasoner_app.reasoner_context_bundle.reconstruction_payload_builder
    import kanda_reasoner_app.reasoner_context_bundle.routing_manifest_builder
    import kanda_reasoner_app.reasoner_context_bundle.schema_models
    import kanda_reasoner_app.reasoner_context_bundle.source_tree_exporter
    import kanda_reasoner_app.reasoner_context_bundle.validation_state_builder
    import kanda_reasoner_app.reasoner_context_collector.collector_active_code
    import kanda_reasoner_app.reasoner_context_collector.collector_ast
    import kanda_reasoner_app.reasoner_context_collector.collector_boundaries
    import kanda_reasoner_app.reasoner_context_collector.collector_boundary_violations
    import kanda_reasoner_app.reasoner_context_collector.collector_bucket_insights
    import kanda_reasoner_app.reasoner_context_collector.collector_buckets
    import kanda_reasoner_app.reasoner_context_collector.collector_canonical_conflicts
    import kanda_reasoner_app.reasoner_context_collector.collector_centrality
    import kanda_reasoner_app.reasoner_context_collector.collector_chains
    import kanda_reasoner_app.reasoner_context_collector.collector_change_impact
    import kanda_reasoner_app.reasoner_context_collector.collector_config
    import kanda_reasoner_app.reasoner_context_collector.collector_config_schema
    import kanda_reasoner_app.reasoner_context_collector.collector_control_flow
    import kanda_reasoner_app.reasoner_context_collector.collector_coverage
    import kanda_reasoner_app.reasoner_context_collector.collector_data_flow
    import kanda_reasoner_app.reasoner_context_collector.collector_docstrings
    import kanda_reasoner_app.reasoner_context_collector.collector_dump_mapper
    import kanda_reasoner_app.reasoner_context_collector.collector_duplicates
    import kanda_reasoner_app.reasoner_context_collector.collector_edit_ready_source
    import kanda_reasoner_app.reasoner_context_collector.collector_entry_bucket_flows
    import kanda_reasoner_app.reasoner_context_collector.collector_entry_points_detail
    import kanda_reasoner_app.reasoner_context_collector.collector_event_propagation
    import kanda_reasoner_app.reasoner_context_collector.collector_feature_registry
    import kanda_reasoner_app.reasoner_context_collector.collector_filters
    import kanda_reasoner_app.reasoner_context_collector.collector_git
    import kanda_reasoner_app.reasoner_context_collector.collector_implementation_chronology
    import kanda_reasoner_app.reasoner_context_collector.collector_insights
    import kanda_reasoner_app.reasoner_context_collector.collector_main
    import kanda_reasoner_app.reasoner_context_collector.collector_module_summary
    import kanda_reasoner_app.reasoner_context_collector.collector_orchestration
    import kanda_reasoner_app.reasoner_context_collector.collector_output
    import kanda_reasoner_app.reasoner_context_collector.collector_ownership
    import kanda_reasoner_app.reasoner_context_collector.collector_persistence_io
    import kanda_reasoner_app.reasoner_context_collector.collector_primary_definition_index
    import kanda_reasoner_app.reasoner_context_collector.collector_priority
    import kanda_reasoner_app.reasoner_context_collector.collector_qt
    import kanda_reasoner_app.reasoner_context_collector.collector_responsibility_overlap
    import kanda_reasoner_app.reasoner_context_collector.collector_roles
    import kanda_reasoner_app.reasoner_context_collector.collector_runtime_feature_attribution
    import kanda_reasoner_app.reasoner_context_collector.collector_runtime_scenarios
    import kanda_reasoner_app.reasoner_context_collector.collector_runtime_trace
    import kanda_reasoner_app.reasoner_context_collector.collector_scope
    import kanda_reasoner_app.reasoner_context_collector.collector_stable_evidence_id_index
    import kanda_reasoner_app.reasoner_context_collector.collector_state
    import kanda_reasoner_app.reasoner_context_collector.collector_state_lifecycle
    import kanda_reasoner_app.reasoner_context_collector.collector_state_mutations
    import kanda_reasoner_app.reasoner_context_collector.collector_subsystems
    import kanda_reasoner_app.reasoner_context_collector.collector_tests
    import kanda_reasoner_app.reasoner_context_collector.collector_ui_actions
    import kanda_reasoner_app.reasoner_context_collector.collector_utils
    import kanda_reasoner_app.reasoner_context_collector.collector_walker
    import kanda_reasoner_app.reasoner_context_collector.collector_warnings
    import kanda_reasoner_app.reasoner_context_collector.collector_web_ai_complete_json_audit
    import kanda_reasoner_app.reasoner_context_collector.collector_web_ai_contract
    import kanda_reasoner_app.reasoner_context_collector.collector_web_ai_file_responsibility_index
    import kanda_reasoner_app.reasoner_context_collector.collector_web_ai_readme
    import kanda_reasoner_app.reasoner_context_collector.collector_web_ai_symbol_index
    import kanda_reasoner_app.reasoner_context_collector.collector_web_ai_test_protection_index
    import kanda_reasoner_app.reasoner_context_collector.collector_widget_layout_index
    import kanda_reasoner_app.reasoner_context_collector.collector_widget_registry
    import kanda_reasoner_app.reasoner_context_collector.collector_widget_summary
    import kanda_reasoner_app.reasoner_context_collector.collector_widget_text_index
    import kanda_reasoner_app.reasoner_context_collector.collector_widget_ui_action_bridge
    import kanda_reasoner_app.reasoner_context_collector.collectors.static_context.collector_documentation_intent
    import kanda_reasoner_app.reasoner_context_collector.collectors.static_context.collector_packaging_metadata
    import kanda_reasoner_app.reasoner_context_collector.complete_json_web_ai_enrichment
    import kanda_reasoner_app.reasoner_context_collector.parsers.static_context.documentation_intent_parser
    import kanda_reasoner_app.reasoner_context_collector.parsers.static_context.packaging_metadata_parser
    import kanda_reasoner_app.reasoner_context_collector.runner
    import kanda_reasoner_app.reasoner_engine.ai_bridge
    import kanda_reasoner_app.reasoner_engine.ai_bridge_help.bridge_signals
    import kanda_reasoner_app.reasoner_engine.ai_bridge_help.deterministic_answers
    import kanda_reasoner_app.reasoner_engine.ai_bridge_help.focus_snippets
    import kanda_reasoner_app.reasoner_engine.ai_bridge_help.grounding_checks
    import kanda_reasoner_app.reasoner_engine.ai_bridge_help.prompt_extraction
    import kanda_reasoner_app.reasoner_engine.ai_bridge_help.prompt_modes
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.analysis_controller
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.answer_presenter
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.json_track
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.profile_controller
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.runtime_controller
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.session_service
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.settings_manager
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.signal_wiring
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.state_models
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.static_context_controller
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.ui_builder
    import kanda_reasoner_app.reasoner_engine.ai_reasoner_main_window_help.ui_components
    import kanda_reasoner_app.reasoner_engine.core.retrieval_section_priorities
    import kanda_reasoner_app.reasoner_engine.help_index
    import kanda_reasoner_app.reasoner_engine.help_index_help.help_index_data
    import kanda_reasoner_app.reasoner_engine.help_index_help.help_index_normalization
    import kanda_reasoner_app.reasoner_engine.help_index_help.help_index_raw
    import kanda_reasoner_app.reasoner_engine.index_loader
    import kanda_reasoner_app.reasoner_engine.index_loader_help.index_builders
    import kanda_reasoner_app.reasoner_engine.index_loader_help.path_resolution
    import kanda_reasoner_app.reasoner_engine.index_loader_help.section_loading
    import kanda_reasoner_app.reasoner_engine.index_loader_help.state_init
    import kanda_reasoner_app.reasoner_engine.project_profile
    import kanda_reasoner_app.reasoner_engine.project_profile_help.built_in_profiles
    import kanda_reasoner_app.reasoner_engine.project_profile_help.inference
    import kanda_reasoner_app.reasoner_engine.project_profile_help.profile_types
    import kanda_reasoner_app.reasoner_engine.project_profile_help.registry
    import kanda_reasoner_app.reasoner_engine.prompt_builder
    import kanda_reasoner_app.reasoner_engine.prompt_builder_help.answer_style
    import kanda_reasoner_app.reasoner_engine.prompt_builder_help.callsite_evidence
    import kanda_reasoner_app.reasoner_engine.prompt_builder_help.prompt_classification
    import kanda_reasoner_app.reasoner_engine.prompt_builder_help.prompt_sections
    import kanda_reasoner_app.reasoner_engine.prompt_builder_help.widget_registry_section
    import kanda_reasoner_app.reasoner_engine.prompt_router_reasoner_manual_router_choice_capture
    import kanda_reasoner_app.reasoner_engine.prompt_router_reasoner_review_store
    import kanda_reasoner_app.reasoner_engine.prompt_router_reasoner_router_mode_state
    import kanda_reasoner_app.reasoner_engine.prompt_router_reasoner_session_capture
    import kanda_reasoner_app.reasoner_engine.prompt_router_reasoner_shadow_bridge
    import kanda_reasoner_app.reasoner_engine.query_router
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.bundle_merge
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.file_context_scoring
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.file_retrieval
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.live_source_fallback
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.profile_support
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.query_intents
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.query_text
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.section_retrieval
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.snippet_retrieval
    import kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.symbol_retrieval
    import kanda_reasoner_app.reasoner_engine.v10_model_registry
    import kanda_reasoner_app.reasoner_engine.v10_qwen_ai_models
    import kanda_reasoner_app.reasoner_runtime_collector.runner
    import kanda_reasoner_app.reasoner_runtime_collector.runtime_runner
    import kanda_reasoner_app.reasoner_runtime_collector.runtime_trace_api
    import kanda_reasoner_app.reasoner_runtime_collector.runtime_trace_writer
    import kanda_reasoner_app.reasoner_symbol_atlas.atlas_report_builder
    import kanda_reasoner_app.reasoner_symbol_atlas.complete_json_adapter
    import kanda_reasoner_app.reasoner_symbol_atlas.evidence_freshness
    import kanda_reasoner_app.reasoner_symbol_atlas.evidence_merger
    import kanda_reasoner_app.reasoner_symbol_atlas.evidence_paths
    import kanda_reasoner_app.reasoner_symbol_atlas.evidence_producer_status
    import kanda_reasoner_app.reasoner_symbol_atlas.existing_code_finder
    import kanda_reasoner_app.reasoner_symbol_atlas.facade_owner_resolver
    import kanda_reasoner_app.reasoner_symbol_atlas.final_status
    import kanda_reasoner_app.reasoner_symbol_atlas.implementation_responsibility_resolver
    import kanda_reasoner_app.reasoner_symbol_atlas.import_analyzer
    import kanda_reasoner_app.reasoner_symbol_atlas.json_active_scope_quality
    import kanda_reasoner_app.reasoner_symbol_atlas.logic_placement_advisor
    import kanda_reasoner_app.reasoner_symbol_atlas.main_helper_mapper
    import kanda_reasoner_app.reasoner_symbol_atlas.module_scanner
    import kanda_reasoner_app.reasoner_symbol_atlas.output_policy
    import kanda_reasoner_app.reasoner_symbol_atlas.owner_classifier
    import kanda_reasoner_app.reasoner_symbol_atlas.pre_patch_gate
    import kanda_reasoner_app.reasoner_symbol_atlas.related_file_finder
    import kanda_reasoner_app.reasoner_symbol_atlas.report_writer
    import kanda_reasoner_app.reasoner_symbol_atlas.schemas
    import kanda_reasoner_app.reasoner_symbol_atlas.shadow_report
    import reasoner_tools_gui
    import reasoner_tools_gui_engineering_safety_panel
    import reasoner_tools_gui_engineering_safety_panel_commands
    import scripts.update_no_isolated_zip_freeze_hint_after_validation
    import scripts.validate_ai_response_patch_delivery
    import tools.kanda_cleanup_audit
    import tools.project_reasoner_v10_deletion_dry_run
    import tools.validate_freeze_after_update_box
    import tools.validate_freeze_after_update_generator_box


def test_architecture_public_contract_import_links_are_static() -> None:
    """Keep this module import-safe at runtime."""
    assert TYPE_CHECKING is False
