# project-path: kanda_reasoner_app/reasoner_context_collector/parsers/static_context/_documentation_intent_scan_helpers.py
"""File discovery and ranking helpers for documentation intent parsing."""

from __future__ import annotations

from pathlib import Path

from ._documentation_intent_extractors import _extract_first_meaningful_paragraph

__all__: list[str] = []


def _normalize_rel_path(path: Path, root: Path) -> str:
    """Support normalize rel path behavior.
    
    Parameters
    ----------
    path : Path
        The file or folder path.
    root : Path
        The root path.
    
    Returns
    -------
    str
        The string result.
    """
    
    return str(path.relative_to(root)).replace("\\", "/")


def _is_ignored_doc_path(path: Path, project_root: Path) -> bool:
    """Support is ignored doc path behavior.
    
    Parameters
    ----------
    path : Path
        The file or folder path.
    project_root : Path
        The project root path.
    
    Returns
    -------
    bool
        True if the condition is met; otherwise, False.
    """
    
    ignored_parts = {
        ".git",
        ".idea",
        ".venv",
        "venv",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        "site-packages",
        "build",
        "dist",
        "cache",
        "logs",
        "outputs",
    }

    try:
        relative_parts = path.relative_to(project_root).parts[:-1]
    except Exception:
        relative_parts = path.parts[:-1]

    for part in relative_parts:
        lowered = str(part).strip().lower()
        if lowered in ignored_parts:
            return True
        if lowered.startswith("."):
            return True
    return False


def _looks_like_vendor_or_font_doc(text: str) -> bool:
    """Support looks like vendor or font doc behavior.
    
    Parameters
    ----------
    text : str
        The text value.
    
    Returns
    -------
    bool
        True if the condition is met; otherwise, False.
    """
    
    lowered = text.lower()
    markers = (
        "included fonts",
        "roboto-",
        "font license",
        "font family",
        "open font license",
        "this package contains fonts",
        "ofl.txt",
    )
    return any(marker in lowered for marker in markers)


def _looks_like_cache_or_generated_doc(path: Path, text: str) -> bool:
    """Support looks like cache or generated doc behavior.
    
    Parameters
    ----------
    path : Path
        The file or folder path.
    text : str
        The text value.
    
    Returns
    -------
    bool
        True if the condition is met; otherwise, False.
    """
    
    lowered = text.lower()
    path_low = str(path).replace("\\", "/").lower()
    if any(token in path_low for token in (".pytest_cache", ".mypy_cache", ".ruff_cache", "site-packages")):
        return True
    markers = (
        "pytest's cache plugin",
        "provides the `--lf` and `--ff` options",
        "generated automatically",
        "do not edit this file directly",
        "autogenerated",
    )
    return any(marker in lowered for marker in markers)


def _read_text_best_effort(path: Path) -> tuple[str, str | None]:
    """Support read text best effort behavior.
    
    Parameters
    ----------
    path : Path
        The file or folder path.
    
    Returns
    -------
    tuple[str, str | None]
        The tuple of values.
    """
    
    try:
        return path.read_text(encoding="utf-8", errors="replace"), None
    except Exception as exc:
        return "", str(exc)


def _doc_rank(path: Path, text: str) -> int:
    """Support doc rank behavior.
    
    Parameters
    ----------
    path : Path
        The file or folder path.
    text : str
        The text value.
    
    Returns
    -------
    int
        The integer result.
    """
    
    path_low = str(path).replace("\\", "/").lower()
    name_low = path.name.lower()
    score = 0
    if name_low == "readme.md":
        score += 220
    elif name_low.startswith("readme"):
        score += 180
    if any(token in path_low for token in ("/docs/architecture", "adr", "architecture")):
        score += 120
    if "/docs/" in path_low:
        score += 80
    if any(token in path_low for token in ("guide", "onboarding", "overview", "design")):
        score += 40
    if _looks_like_vendor_or_font_doc(text):
        score -= 250
    if _looks_like_cache_or_generated_doc(path, text):
        score -= 300
    if name_low.endswith(".txt"):
        score -= 30
    if _extract_first_meaningful_paragraph(text):
        score += 40
    return score


def _extract_best_purpose_summary(
    candidates: list[tuple[int, str, str]],
) -> tuple[str, str]:
    """Support extract best purpose summary behavior.
    
    Parameters
    ----------
    candidates : list[tuple[int, str, str]]
        The candidates value.
    
    Returns
    -------
    tuple[str, str]
        The tuple of values.
    """
    
    if not candidates:
        return "", "unknown"
    best_rank, _source_file, summary = sorted(candidates, key=lambda item: item[0], reverse=True)[0]
    if best_rank >= 220:
        confidence = "high"
    elif best_rank >= 120:
        confidence = "medium"
    elif best_rank > 0:
        confidence = "low"
    else:
        confidence = "unknown"
    return summary, confidence


def _discover_doc_files(root, *args, **kwargs):
    """Support discover doc files behavior.
    
    Parameters
    ----------
    root : object
        The root path.
    *args : object
        The positional arguments.
    **kwargs : object
        The kwargs value.
    """
    
    from kanda_reasoner_app.reasoner_context_collector.collector_scope import iter_project_documentation_files
    return list(iter_project_documentation_files(root))
