"""Public package surface for the Brain Navigator box scaffold."""

from __future__ import annotations

from .contract import (
    BRAIN_NAVIGATOR_BOX_ID,
    BRAIN_NAVIGATOR_TAB_ID,
    BRAIN_NAVIGATOR_TAB_LABEL,
    BrainNavigatorContractSummary,
    build_brain_web_channel_bootstrap_script,
    build_brain_web_view_scaffold_html,
    build_neural_architecture_asset_preview_html,
    build_neural_architecture_marker_data_js,
    build_neural_architecture_floating_window_data_js,
    get_neural_architecture_floating_window_summary,
    list_neural_architecture_floating_windows,
    get_neural_architecture_pulse_marker_summary,
    list_neural_architecture_pulse_markers,
    get_neural_architecture_preview_summary,
    create_visible_neural_architecture_brain_tab,
    get_visible_neural_architecture_tab_summary,
    create_neural_architecture_preview,
    build_neural_architecture_preview_html,
    create_brain_navigator_tab,
    create_brain_web_bridge,
    create_brain_web_view_scaffold,
    get_brain_navigator_contract_summary,
    get_brain_navigator_freeze_snapshot,
    get_neural_architecture_visual_spec,
    get_brain_mesh_data_summary,
    get_brain_mesh_data_js,
    get_brain_web_bridge_summary,
    get_brain_web_view_scaffold_summary,
    normalize_brain_region_id,
)

__all__ = [
    "BRAIN_NAVIGATOR_BOX_ID",
    "BRAIN_NAVIGATOR_TAB_ID",
    "BRAIN_NAVIGATOR_TAB_LABEL",
    "BrainNavigatorContractSummary",
    "build_brain_web_channel_bootstrap_script",
    "build_brain_web_view_scaffold_html",
    "build_neural_architecture_asset_preview_html",
    "build_neural_architecture_marker_data_js",
    "list_neural_architecture_floating_windows",
    "get_neural_architecture_floating_window_summary",
    "build_neural_architecture_floating_window_data_js",
    "get_neural_architecture_pulse_marker_summary",
    "list_neural_architecture_pulse_markers",
    "get_neural_architecture_preview_summary",
    "create_visible_neural_architecture_brain_tab",
    "get_visible_neural_architecture_tab_summary",
    "create_neural_architecture_preview",
    "build_neural_architecture_preview_html",
    "create_brain_navigator_tab",
    "create_brain_web_bridge",
    "create_brain_web_view_scaffold",
    "get_brain_navigator_contract_summary",
    "get_brain_navigator_freeze_snapshot",
    "get_neural_architecture_visual_spec",
    "get_brain_mesh_data_summary",
    "get_brain_mesh_data_js",
    "get_brain_web_bridge_summary",
    "get_brain_web_view_scaffold_summary",
    "normalize_brain_region_id",
]
