
# project-path: kanda_reasoner_app/reasoner_symbol_atlas/__init__.py
from .review_session import (
    ProjectSymbolAtlasReviewSessionIdentity,
    reasoner_symbol_atlas_review_session,
)
from .reference_folder_policy import (
    PROJECT_SYMBOL_ATLAS_INACTIVE_REFERENCE_FOLDERS,
    build_reasoner_symbol_atlas_reference_path_markers,
    is_reasoner_symbol_atlas_reference_path,
    iter_reasoner_symbol_atlas_reference_evidence_dirs,
    normalize_reasoner_symbol_atlas_policy_path,
)
from .evidence_merger import (
    PROJECT_SYMBOL_ATLAS_MERGE_STATUS_JSON_ADVISORY,
    PROJECT_SYMBOL_ATLAS_MERGE_STATUS_JSON_ENRICHED,
    PROJECT_SYMBOL_ATLAS_MERGE_STATUS_JSON_REJECTED,
    PROJECT_SYMBOL_ATLAS_MERGE_STATUS_LIVE_ONLY,
    ProjectSymbolAtlasEvidenceMergeOptions,
    ProjectSymbolAtlasEvidenceMergeSummary,
    build_reasoner_symbol_atlas_live_json_merge_report,
    build_reasoner_symbol_atlas_merged_evidence_report,
    merge_reasoner_symbol_atlas_live_and_json_evidence,
)
from .evidence_freshness import (
    PROJECT_SYMBOL_ATLAS_EVIDENCE_STATUS_FRESH,
    PROJECT_SYMBOL_ATLAS_EVIDENCE_STATUS_INVALID_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_EVIDENCE_STATUS_MISSING_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_EVIDENCE_STATUS_PROBABLY_STALE,
    PROJECT_SYMBOL_ATLAS_EVIDENCE_STATUS_STALE,
    PROJECT_SYMBOL_ATLAS_EVIDENCE_STATUS_WRONG_PROJECT,
    ProjectSymbolAtlasEvidenceFreshnessOptions,
    ProjectSymbolAtlasEvidenceFreshnessSummary,
    build_reasoner_symbol_atlas_evidence_freshness_report,
    check_reasoner_symbol_atlas_evidence_freshness,
)
from .complete_json_adapter import (
    PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_RECOMMENDED_SECTIONS,
    PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_REQUIRED_SECTIONS,
    PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_INVALID_JSON,
    PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_MISSING_JSON,
    PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_MISSING_SECTIONS,
    PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_READY,
    ProjectSymbolAtlasCompleteJsonOptions,
    ProjectSymbolAtlasCompleteJsonSummary,
    build_reasoner_symbol_atlas_complete_json_report,
    collect_reasoner_symbol_atlas_complete_json_files,
    expected_reasoner_symbol_atlas_complete_json_name,
    load_reasoner_symbol_atlas_complete_json,
    summarize_reasoner_symbol_atlas_complete_json,
)
"""Project Symbol Atlas foundations for Kanda Reasoner."""

from .import_analyzer import (
    ProjectSymbolAtlasImportAnalysisOptions,
    analyze_reasoner_symbol_atlas_imports,
    build_reasoner_symbol_atlas_import_report,
    collect_reasoner_symbol_atlas_imports,
)
from .module_scanner import (
    ProjectSymbolAtlasModuleScanOptions,
    build_reasoner_symbol_atlas_module_report,
    collect_reasoner_symbol_atlas_modules,
    reasoner_symbol_atlas_module_name_for_path,
)
from .symbol_indexer import (
    ProjectSymbolAtlasSymbolIndexOptions,
    build_reasoner_symbol_atlas_symbol_report,
    collect_reasoner_symbol_atlas_symbols,
    index_reasoner_symbol_atlas_modules,
)
from .owner_classifier import (
    ProjectSymbolAtlasOwnerClassifyOptions,
    build_reasoner_symbol_atlas_owner_report,
    classify_reasoner_symbol_atlas_owners,
)
from .shadow_report import (
    ProjectSymbolAtlasShadowReportOptions,
    build_reasoner_symbol_atlas_shadow_report,
    collect_reasoner_symbol_atlas_shadow_findings,
)
from .report_writer import (
    default_reasoner_symbol_atlas_report_dir,
    format_reasoner_symbol_atlas_markdown,
    reasoner_symbol_atlas_report_stem,
    write_reasoner_symbol_atlas_report,
)
from .schemas import (
    PROJECT_ATLAS_DEFAULT_OWNER_ROLE,
    PROJECT_ATLAS_DEFAULT_REPORT_TYPE,
    PROJECT_ATLAS_DEFAULT_SYMBOL_KIND,
    PROJECT_ATLAS_VALID_OWNER_ROLES,
    PROJECT_ATLAS_VALID_REPORT_TYPES,
    PROJECT_ATLAS_VALID_SYMBOL_KINDS,
    ProjectAtlasWriteResult,
    ProjectModuleRecord,
    ProjectSymbol,
    ProjectSymbolAtlasReport,
    ProjectSymbolQuery,
    ProjectSymbolQueryResult,
    make_project_atlas_report_id,
    make_project_atlas_timestamp,
    normalize_project_atlas_owner_role,
    normalize_project_atlas_report_type,
    normalize_project_atlas_sequence,
    normalize_project_atlas_symbol_kind,
    normalize_project_atlas_text,
)

from .logic_placement_advisor import (
    PROJECT_SYMBOL_ATLAS_PLACEMENT_OWNER_BOXES,
    PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_INSUFFICIENT_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_NEEDS_OWNER_REVIEW,
    PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_READY,
    PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_WRONG_TARGET,
    ProjectSymbolAtlasLogicPlacementDecision,
    ProjectSymbolAtlasLogicPlacementOptions,
    advise_reasoner_symbol_atlas_logic_placement,
    build_reasoner_symbol_atlas_logic_placement_report,
)

from .facade_owner_resolver import (
    PROJECT_SYMBOL_ATLAS_FACADE_STATUS_INSUFFICIENT_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_FACADE_STATUS_NEEDS_OWNER_REVIEW,
    PROJECT_SYMBOL_ATLAS_FACADE_STATUS_NO_FACADE,
    PROJECT_SYMBOL_ATLAS_FACADE_STATUS_OWNER_NOT_FOUND,
    PROJECT_SYMBOL_ATLAS_FACADE_STATUS_READY,
    PROJECT_SYMBOL_ATLAS_FACADE_STATUS_TARGET_NOT_FOUND,
    ProjectSymbolAtlasFacadeOwnerDecision,
    ProjectSymbolAtlasFacadeOwnerOptions,
    build_reasoner_symbol_atlas_facade_owner_report,
    resolve_reasoner_symbol_atlas_facade_owner,
)

from .main_helper_mapper import (
    PROJECT_SYMBOL_ATLAS_HELPER_SUFFIXES,
    PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_AMBIGUOUS_MAIN,
    PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_INSUFFICIENT_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_NO_HELPERS_FOUND,
    PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_READY,
    PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_TARGET_NOT_FOUND,
    ProjectSymbolAtlasMainHelperDecision,
    ProjectSymbolAtlasMainHelperOptions,
    build_reasoner_symbol_atlas_main_helper_report,
    map_reasoner_symbol_atlas_main_helpers,
)

from .implementation_responsibility_resolver import (
    PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_INSUFFICIENT_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_NEEDS_OWNER_REVIEW,
    PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_READY,
    PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_TARGET_NOT_FOUND,
    PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_WRONG_TARGET,
    ProjectSymbolAtlasImplementationResponsibilityDecision,
    ProjectSymbolAtlasImplementationResponsibilityOptions,
    build_reasoner_symbol_atlas_implementation_responsibility_report,
    resolve_reasoner_symbol_atlas_implementation_responsibility,
)


from .related_file_finder import (
    PROJECT_SYMBOL_ATLAS_RELATED_STATUS_INSUFFICIENT_EVIDENCE,
    PROJECT_SYMBOL_ATLAS_RELATED_STATUS_NO_RELATED_FILES,
    PROJECT_SYMBOL_ATLAS_RELATED_STATUS_READY,
    PROJECT_SYMBOL_ATLAS_RELATED_STATUS_TARGET_NOT_FOUND,
    PROJECT_SYMBOL_ATLAS_RELATED_SUPPORT_SUFFIXES,
    ProjectSymbolAtlasRelatedFileDecision,
    ProjectSymbolAtlasRelatedFileOptions,
    build_reasoner_symbol_atlas_related_file_report,
    find_reasoner_symbol_atlas_related_files,
)


from .json_active_scope_quality import (
    ACTIVE_PATH_FIELD_NAMES,
    ACTIVE_PATH_SECTIONS,
    PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_ACTIVE_LEAK,
    PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_CLEAN,
    PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_INVALID_JSON,
    PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_MISSING_JSON,
    PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_TEXT_ONLY,
    ProjectSymbolAtlasJsonActiveScopeOccurrence,
    ProjectSymbolAtlasJsonActiveScopeQualityOptions,
    ProjectSymbolAtlasJsonActiveScopeQualitySummary,
    TRUTH_TEXT_FIELD_NAMES,
    build_reasoner_symbol_atlas_json_active_scope_report,
    check_reasoner_symbol_atlas_json_active_scope_quality,
)

__all__ = [
    "ProjectSymbolAtlasReviewSessionIdentity",
    "reasoner_symbol_atlas_review_session",
    "ACTIVE_PATH_FIELD_NAMES",
    "ACTIVE_PATH_SECTIONS",
    "PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_ACTIVE_LEAK",
    "PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_CLEAN",
    "PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_INVALID_JSON",
    "PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_MISSING_JSON",
    "PROJECT_SYMBOL_ATLAS_JSON_QUALITY_STATUS_TEXT_ONLY",
    "ProjectSymbolAtlasJsonActiveScopeOccurrence",
    "ProjectSymbolAtlasJsonActiveScopeQualityOptions",
    "ProjectSymbolAtlasJsonActiveScopeQualitySummary",
    "TRUTH_TEXT_FIELD_NAMES",
    "build_reasoner_symbol_atlas_json_active_scope_report",
    "check_reasoner_symbol_atlas_json_active_scope_quality",
    "PROJECT_SYMBOL_ATLAS_RELATED_STATUS_INSUFFICIENT_EVIDENCE",
    "PROJECT_SYMBOL_ATLAS_RELATED_STATUS_NO_RELATED_FILES",
    "PROJECT_SYMBOL_ATLAS_RELATED_STATUS_READY",
    "PROJECT_SYMBOL_ATLAS_RELATED_STATUS_TARGET_NOT_FOUND",
    "PROJECT_SYMBOL_ATLAS_RELATED_SUPPORT_SUFFIXES",
    "ProjectSymbolAtlasRelatedFileDecision",
    "ProjectSymbolAtlasRelatedFileOptions",
    "build_reasoner_symbol_atlas_related_file_report",
    "find_reasoner_symbol_atlas_related_files",
    "PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_INSUFFICIENT_EVIDENCE",
    "PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_NEEDS_OWNER_REVIEW",
    "PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_READY",
    "PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_TARGET_NOT_FOUND",
    "PROJECT_SYMBOL_ATLAS_RESPONSIBILITY_STATUS_WRONG_TARGET",
    "ProjectSymbolAtlasImplementationResponsibilityDecision",
    "ProjectSymbolAtlasImplementationResponsibilityOptions",
    "build_reasoner_symbol_atlas_implementation_responsibility_report",
    "resolve_reasoner_symbol_atlas_implementation_responsibility",
    "PROJECT_SYMBOL_ATLAS_HELPER_SUFFIXES",
    "PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_AMBIGUOUS_MAIN",
    "PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_INSUFFICIENT_EVIDENCE",
    "PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_NO_HELPERS_FOUND",
    "PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_READY",
    "PROJECT_SYMBOL_ATLAS_MAIN_HELPER_STATUS_TARGET_NOT_FOUND",
    "ProjectSymbolAtlasMainHelperDecision",
    "ProjectSymbolAtlasMainHelperOptions",
    "build_reasoner_symbol_atlas_main_helper_report",
    "map_reasoner_symbol_atlas_main_helpers",
    "PROJECT_SYMBOL_ATLAS_FACADE_STATUS_INSUFFICIENT_EVIDENCE",
    "PROJECT_SYMBOL_ATLAS_FACADE_STATUS_NEEDS_OWNER_REVIEW",
    "PROJECT_SYMBOL_ATLAS_FACADE_STATUS_NO_FACADE",
    "PROJECT_SYMBOL_ATLAS_FACADE_STATUS_OWNER_NOT_FOUND",
    "PROJECT_SYMBOL_ATLAS_FACADE_STATUS_READY",
    "PROJECT_SYMBOL_ATLAS_FACADE_STATUS_TARGET_NOT_FOUND",
    "ProjectSymbolAtlasFacadeOwnerDecision",
    "ProjectSymbolAtlasFacadeOwnerOptions",
    "build_reasoner_symbol_atlas_facade_owner_report",
    "resolve_reasoner_symbol_atlas_facade_owner",
    "PROJECT_SYMBOL_ATLAS_PLACEMENT_OWNER_BOXES",
    "PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_INSUFFICIENT_EVIDENCE",
    "PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_NEEDS_OWNER_REVIEW",
    "PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_READY",
    "PROJECT_SYMBOL_ATLAS_PLACEMENT_STATUS_WRONG_TARGET",
    "ProjectSymbolAtlasLogicPlacementDecision",
    "ProjectSymbolAtlasLogicPlacementOptions",
    "advise_reasoner_symbol_atlas_logic_placement",
    "build_reasoner_symbol_atlas_logic_placement_report",
    "PROJECT_SYMBOL_ATLAS_MERGE_STATUS_JSON_ADVISORY",
    "PROJECT_SYMBOL_ATLAS_MERGE_STATUS_JSON_ENRICHED",
    "PROJECT_SYMBOL_ATLAS_MERGE_STATUS_JSON_REJECTED",
    "PROJECT_SYMBOL_ATLAS_MERGE_STATUS_LIVE_ONLY",
    "ProjectSymbolAtlasEvidenceMergeOptions",
    "ProjectSymbolAtlasEvidenceMergeSummary",
    "build_reasoner_symbol_atlas_live_json_merge_report",
    "build_reasoner_symbol_atlas_merged_evidence_report",
    "merge_reasoner_symbol_atlas_live_and_json_evidence",
    "PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_RECOMMENDED_SECTIONS",
    "PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_REQUIRED_SECTIONS",
    "PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_INVALID_JSON",
    "PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_MISSING_JSON",
    "PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_MISSING_SECTIONS",
    "PROJECT_SYMBOL_ATLAS_COMPLETE_JSON_STATUS_READY",
    "ProjectSymbolAtlasCompleteJsonOptions",
    "ProjectSymbolAtlasCompleteJsonSummary",
    "build_reasoner_symbol_atlas_complete_json_report",
    "collect_reasoner_symbol_atlas_complete_json_files",
    "expected_reasoner_symbol_atlas_complete_json_name",
    "load_reasoner_symbol_atlas_complete_json",
    "summarize_reasoner_symbol_atlas_complete_json",
    "PROJECT_ATLAS_DEFAULT_OWNER_ROLE",
    "PROJECT_ATLAS_DEFAULT_REPORT_TYPE",
    "PROJECT_ATLAS_DEFAULT_SYMBOL_KIND",
    "PROJECT_ATLAS_VALID_OWNER_ROLES",
    "PROJECT_ATLAS_VALID_REPORT_TYPES",
    "PROJECT_ATLAS_VALID_SYMBOL_KINDS",
    "ProjectAtlasWriteResult",
    "ProjectModuleRecord",
    "ProjectSymbol",
    "ProjectSymbolAtlasImportAnalysisOptions",
    "ProjectSymbolAtlasModuleScanOptions",
    "ProjectSymbolAtlasSymbolIndexOptions",
    "ProjectSymbolAtlasReport",
    "classify_reasoner_symbol_atlas_owners",
    "build_reasoner_symbol_atlas_owner_report",
    "ProjectSymbolAtlasOwnerClassifyOptions",
    "ProjectSymbolQuery",
    "ProjectSymbolQueryResult",
    "analyze_reasoner_symbol_atlas_imports",
    "build_reasoner_symbol_atlas_import_report",
    "build_reasoner_symbol_atlas_module_report",
    "build_reasoner_symbol_atlas_symbol_report",
    "collect_reasoner_symbol_atlas_imports",
    "collect_reasoner_symbol_atlas_modules",
    "collect_reasoner_symbol_atlas_symbols",
    "index_reasoner_symbol_atlas_modules",
    "default_reasoner_symbol_atlas_report_dir",
    "format_reasoner_symbol_atlas_markdown",
    "make_project_atlas_report_id",
    "make_project_atlas_timestamp",
    "normalize_project_atlas_owner_role",
    "normalize_project_atlas_report_type",
    "normalize_project_atlas_sequence",
    "normalize_project_atlas_symbol_kind",
    "normalize_project_atlas_text",
    "reasoner_symbol_atlas_module_name_for_path",
    "reasoner_symbol_atlas_report_stem",
    "write_reasoner_symbol_atlas_report",
    "ProjectSymbolAtlasShadowReportOptions",
    "build_reasoner_symbol_atlas_shadow_report",
    "collect_reasoner_symbol_atlas_shadow_findings",
]
