# project-path: large_file_refactor_planner/workbench_post_apply_validator.py
"""Post-apply validation for exact-token Large File Refactor source apply."""

from __future__ import annotations

import ast
from dataclasses import asdict, dataclass, field
import hashlib
import json
from pathlib import Path
from typing import Any

from .workbench_project_support_paths import preview_runs_root
from .workbench_project_support_paths import (
    preview_root_blockers as project_preview_root_blockers,
)
from .models import SCHEMA_VERSION
from .module_size_policy import check_resulting_module_size
from .workbench_guarded_source_apply import GuardedSourceApplyResult
from .workbench_source_payload_builder import SourceApplyPayloadReadinessResult
from .workbench_post_apply_ruff_validation import validate_and_write_post_apply_ruff

__all__ = [
    "POST_APPLY_VALIDATION_FEATURE_ID",
    "WorkbenchPostApplyValidationResult",
    "validate_and_write_post_apply",
]

POST_APPLY_VALIDATION_FEATURE_ID = (
    "architecture-review-large-file-refactor-post-apply-validation-v1"
)
_POST_APPLY_REPORT = "SOURCE_APPLY_POST_APPLY_VALIDATION.json"
_PROTECTED_PARTS = {
    ".project_reference",
    "_project_reference",
    "project_freeze_after_update",
    "project_error_memory",
    "project_freeze_ledger",
    "show_project_to_AI",
    "_show_project_to_AI",
}


@dataclass(frozen=True)
class PostApplyValidationResult:
    """Validation result after guarded source apply."""

    schema_version: str
    feature_id: str
    status: str
    structural_status: str
    behavior_status: str
    target_file: str
    preview_root: str
    report_path: str
    rollback_manifest_path: str
    checked_files: list[str] = field(default_factory=list)
    blockers: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    checked_rules: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-ready post-apply validation result."""
        return asdict(self)


# Compatibility alias kept for Workbench modules generated by earlier trains.
# Do not remove without updating every dependent import chain.
WorkbenchPostApplyValidationResult = PostApplyValidationResult


def validate_and_write_post_apply(
    *,
    apply_result: GuardedSourceApplyResult | None,
    source_payload: SourceApplyPayloadReadinessResult | None,
    active_project_root: str,
) -> PostApplyValidationResult:
    """Validate files written by guarded source apply and write evidence."""
    project_root = Path(active_project_root).resolve()
    blockers = _entry_blockers(apply_result, source_payload)
    preview_root = (
        Path(apply_result.preview_root).resolve()
        if apply_result
        else _daily_preview_root(project_root)
    )
    target = (
        Path(apply_result.target_file).resolve() if apply_result else Path("").resolve()
    )
    checked: list[str] = []
    if apply_result and source_payload:
        blockers.extend(_root_blockers(project_root, preview_root, target))
        for file_record in source_payload.files:
            destination = Path(file_record.destination_path).resolve()
            checked.append(str(destination))
            blockers.extend(
                _validate_written_file(
                    destination, file_record.content_hash, project_root
                )
            )
        if not Path(apply_result.rollback_manifest_path).is_file():
            blockers.append("ROLLBACK_MANIFEST_MISSING")
        ruff_result = validate_and_write_post_apply_ruff(
            active_project_root=project_root,
            preview_root=preview_root,
            checked_files=checked,
            skip_due_to_prior_blockers=bool(blockers),
        )
        blockers.extend(ruff_result.blockers)
        warnings = [*_warnings(), *ruff_result.warnings]
        checked_rules = [*_checked_rules(), *ruff_result.checked_rules]
    else:
        warnings = _warnings()
        checked_rules = _checked_rules()
    status = "post_apply_validated" if not blockers else "blocked"
    result = PostApplyValidationResult(
        schema_version=SCHEMA_VERSION,
        feature_id=POST_APPLY_VALIDATION_FEATURE_ID,
        status=status,
        structural_status="STRUCTURAL_PASS_WITH_WARNINGS"
        if not blockers
        else "STRUCTURAL_FAIL",
        behavior_status="BEHAVIOR_VALIDATION_NOT_RUN",
        target_file=str(target) if apply_result else "",
        preview_root=str(preview_root),
        report_path=str(preview_root / _POST_APPLY_REPORT),
        rollback_manifest_path=apply_result.rollback_manifest_path
        if apply_result
        else "",
        checked_files=checked,
        blockers=sorted(set(blockers)),
        warnings=sorted(set(warnings)),
        checked_rules=list(dict.fromkeys(checked_rules)),
    )
    _write_report(result)
    return result


def _entry_blockers(
    apply_result: GuardedSourceApplyResult | None,
    payload: SourceApplyPayloadReadinessResult | None,
) -> list[str]:
    """Return missing prerequisite blockers."""
    blockers: list[str] = []
    if apply_result is None or apply_result.status != "applied":
        blockers.append("GUARDED_SOURCE_APPLY_NOT_SUCCESSFUL")
    if payload is None or payload.status != "source_apply_payload_ready":
        blockers.append("SOURCE_APPLY_PAYLOAD_NOT_READY")
    if apply_result is not None and apply_result.import_rewrite_enabled:
        blockers.append("IMPORT_REWRITE_MUST_REMAIN_DISABLED")
    return blockers


def _validate_written_file(
    path: Path, expected_hash: str, project_root: Path
) -> list[str]:
    """Return blockers for one expected applied file."""
    blockers: list[str] = []
    if not _is_relative_to(path, project_root):
        blockers.append("APPLIED_FILE_OUTSIDE_PROJECT_ROOT:" + str(path))
    if _protected_parts(path):
        blockers.append("APPLIED_FILE_IN_PROTECTED_ROOT:" + str(path))
    if not path.is_file():
        blockers.append("APPLIED_FILE_MISSING:" + str(path))
        return blockers
    raw = path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected_hash:
        blockers.append("APPLIED_FILE_HASH_MISMATCH:" + str(path))
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        blockers.append("APPLIED_FILE_NOT_UTF8:" + str(path))
        return blockers
    if "KANDA PREVIEW ARTIFACT" in text:
        blockers.append("PREVIEW_WATERMARK_LEAKED_TO_SOURCE:" + str(path))
    blockers.extend(check_resulting_module_size(text, relative_path=path.name).blockers)
    try:
        compile(text, str(path), "exec")
        ast.parse(text)
    except SyntaxError:
        blockers.append("APPLIED_FILE_SYNTAX_INVALID:" + str(path))
    return blockers


def _root_blockers(project_root: Path, preview_root: Path, target: Path) -> list[str]:
    """Validate preview and target roots after apply."""
    blockers: list[str] = []
    if not _is_relative_to(target, project_root):
        blockers.append("TARGET_OUTSIDE_PROJECT_ROOT")
    blockers.extend(project_preview_root_blockers(project_root, preview_root))
    return blockers


def _write_report(result: PostApplyValidationResult) -> None:
    """Write post-apply validation evidence inside preview root."""
    path = Path(result.report_path).resolve()
    root = Path(result.preview_root).resolve()
    if not _is_relative_to(path, root):
        raise RuntimeError("Post-apply report path outside preview root: " + str(path))
    path.write_text(
        json.dumps(result.to_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _checked_rules() -> list[str]:
    """Return stable checked-rule labels."""
    return [
        "guarded_source_apply_succeeded_before_post_apply_validation",
        "expected_files_exist",
        "applied_hashes_match_source_payload",
        "applied_files_compile_and_parse",
        "preview_watermark_not_in_source",
        "rollback_manifest_exists",
        "import_rewrite_disabled",
        "behavior_validation_not_claimed_without_tests",
    ]


def _warnings() -> list[str]:
    """Return stable post-apply warning labels."""
    return [
        "STRUCTURAL_VALIDATION_ONLY",
        "BEHAVIOR_VALIDATION_NOT_RUN",
        "IMPORT_MIGRATION_REMAINS_PREVIEW_ONLY",
    ]


def _daily_preview_root(project_root: Path) -> Path:
    """Return dynamic selected-project Preview support root."""
    return preview_runs_root(project_root)


def _protected_parts(path: Path) -> list[str]:
    """Return protected path parts found in a path."""
    return [part for part in path.resolve().parts if part in _PROTECTED_PARTS]


def _is_relative_to(path: Path, root: Path) -> bool:
    """Return True if path is inside root after resolution."""
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False
