# project-path: kanda_reasoner_app/source_hygiene/shadow_planner.py
"""Read-only planning for shadow conflict corrections."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .schemas import SourceHygieneFinding, SourceHygieneReport

__all__ = [
    "ShadowCorrectionPlanItem",
    "build_shadow_conflict_plan",
    "classify_shadow_finding",
    "finding_to_plan_item",
]

SAFE_MECHANICAL_FIX = "safe_mechanical_fix"
REQUIRES_OWNER_DECISION = "requires_owner_decision"
REQUIRES_COMPATIBILITY_FACADE = "requires_compatibility_facade"
DO_NOT_TOUCH = "do_not_touch"

_CODE_CLASSIFICATIONS = {
    "WILDCARD_IMPORT_IN_FACADE": SAFE_MECHANICAL_FIX,
    "FACADE_WITHOUT_ALL": SAFE_MECHANICAL_FIX,
    "UNBOUND_ALL_EXPORT": SAFE_MECHANICAL_FIX,
    "DYNAMIC_ALL_EXPORT": REQUIRES_OWNER_DECISION,
    "DUPLICATE_PUBLIC_SYMBOL": REQUIRES_OWNER_DECISION,
    "BEHAVIOR_DEFINED_IN_FACADE": REQUIRES_COMPATIBILITY_FACADE,
    "RUNTIME_LOGIC_IN_FACADE": REQUIRES_COMPATIBILITY_FACADE,
    "SHADOW_AUDIT_PARSE_ERROR": DO_NOT_TOUCH,
    "SHADOW_AUDIT_READ_ERROR": DO_NOT_TOUCH,
}

_CLASSIFICATION_GUIDANCE = {
    SAFE_MECHANICAL_FIX: (
        "This finding may be fixable mechanically after focused import tests prove the "
        "public contract is preserved."
    ),
    REQUIRES_OWNER_DECISION: (
        "This finding needs a canonical owner decision before any source change."
    ),
    REQUIRES_COMPATIBILITY_FACADE: (
        "This finding usually needs behavior moved to an owner module while keeping "
        "the old import path as a compatibility facade when needed."
    ),
    DO_NOT_TOUCH: (
        "Do not edit this file through the shadow planner. Repair readability or "
        "syntax first, then rerun the audit."
    ),
}


@dataclass(frozen=True)
class ShadowCorrectionPlanItem:
    """One read-only correction plan item for a shadow audit finding."""

    source_code: str
    path: str
    line: int | None
    classification: str
    proposed_action: str
    required_tests: tuple[str, ...]
    rollback_plan: str
    evidence: dict[str, object]

    def to_finding(self) -> SourceHygieneFinding:
        """Represent this plan item as a source hygiene finding."""
        return SourceHygieneFinding(
            code="SHADOW_CORRECTION_PLAN_ITEM",
            path=self.path,
            line=self.line,
            severity="info",
            confidence="medium",
            message=self.classification + ": " + self.proposed_action,
            evidence={
                "source_code": self.source_code,
                "classification": self.classification,
                "required_tests": list(self.required_tests),
                "rollback_plan": self.rollback_plan,
                "source_evidence": dict(self.evidence),
            },
            suggested_action=self.proposed_action,
        )


def classify_shadow_finding(finding: SourceHygieneFinding | dict[str, object]) -> str:
    """Return the safest correction class for a shadow audit finding."""
    code = _finding_code(finding)
    return _CODE_CLASSIFICATIONS.get(code, REQUIRES_OWNER_DECISION)


def finding_to_plan_item(
    finding: SourceHygieneFinding | dict[str, object],
) -> ShadowCorrectionPlanItem:
    """Convert one audit finding into a conservative correction plan item."""
    code = _finding_code(finding)
    classification = classify_shadow_finding(finding)
    return ShadowCorrectionPlanItem(
        source_code=code,
        path=_finding_path(finding),
        line=_finding_line(finding),
        classification=classification,
        proposed_action=_proposed_action_for(code, classification),
        required_tests=_required_tests_for(code, classification),
        rollback_plan=_rollback_plan_for(classification),
        evidence=_finding_evidence(finding),
    )


def build_shadow_conflict_plan(
    audit_report: SourceHygieneReport | dict[str, object],
    project_root: str | Path | None = None,
) -> SourceHygieneReport:
    """Build a read-only correction plan from a shadow conflict audit report."""
    findings = _report_findings(audit_report)
    plan_items = [finding_to_plan_item(finding) for finding in findings]
    plan_findings = tuple(item.to_finding() for item in plan_items)
    counts = _classification_counts(plan_items)
    root = str(project_root or _report_project_root(audit_report) or "")
    summary = _format_summary(counts, len(plan_items))
    return SourceHygieneReport(
        project_root=root,
        report_type="shadow_conflict_plan",
        summary=summary,
        findings=plan_findings,
        input_sources=("shadow_conflict_audit",),
    )


def _report_findings(report: SourceHygieneReport | dict[str, object]) -> tuple[SourceHygieneFinding | dict[str, object], ...]:
    """Support report findings behavior.
    
    Parameters
    ----------
    report : SourceHygieneReport | dict[str, object]
        The report value.
    
    Returns
    -------
    tuple[SourceHygieneFinding | dict[str, object], ...]
        The tuple of values.
    """
    
    if isinstance(report, SourceHygieneReport):
        return report.findings
    raw_findings = report.get("findings", ())
    if not isinstance(raw_findings, Iterable):
        return ()
    return tuple(item for item in raw_findings if isinstance(item, dict))


def _report_project_root(report: SourceHygieneReport | dict[str, object]) -> str:
    """Support report project root behavior.
    
    Parameters
    ----------
    report : SourceHygieneReport | dict[str, object]
        The report value.
    
    Returns
    -------
    str
        The string result.
    """
    
    if isinstance(report, SourceHygieneReport):
        return str(report.project_root)
    value = report.get("project_root", "")
    return str(value)


def _finding_code(finding: SourceHygieneFinding | dict[str, object]) -> str:
    """Support finding code behavior.
    
    Parameters
    ----------
    finding : SourceHygieneFinding | dict[str, object]
        The finding value.
    
    Returns
    -------
    str
        The string result.
    """
    
    if isinstance(finding, SourceHygieneFinding):
        return finding.code
    return str(finding.get("code", ""))


def _finding_path(finding: SourceHygieneFinding | dict[str, object]) -> str:
    """Support finding path behavior.
    
    Parameters
    ----------
    finding : SourceHygieneFinding | dict[str, object]
        The finding value.
    
    Returns
    -------
    str
        The string result.
    """
    
    if isinstance(finding, SourceHygieneFinding):
        return finding.path
    return str(finding.get("path", ""))


def _finding_line(finding: SourceHygieneFinding | dict[str, object]) -> int | None:
    """Support finding line behavior.
    
    Parameters
    ----------
    finding : SourceHygieneFinding | dict[str, object]
        The finding value.
    
    Returns
    -------
    int | None
        The integer result.
    """
    
    if isinstance(finding, SourceHygieneFinding):
        return finding.line
    line = finding.get("line")
    if isinstance(line, int):
        return line
    return None


def _finding_evidence(finding: SourceHygieneFinding | dict[str, object]) -> dict[str, object]:
    """Support finding evidence behavior.
    
    Parameters
    ----------
    finding : SourceHygieneFinding | dict[str, object]
        The finding value.
    
    Returns
    -------
    dict[str, object]
        The mapped values.
    """
    
    if isinstance(finding, SourceHygieneFinding):
        return dict(finding.evidence)
    evidence = finding.get("evidence", {})
    if isinstance(evidence, dict):
        return dict(evidence)
    return {}


def _proposed_action_for(code: str, classification: str) -> str:
    """Support proposed action for behavior.
    
    Parameters
    ----------
    code : str
        The code value.
    classification : str
        The classification value.
    
    Returns
    -------
    str
        The string result.
    """
    
    if code == "WILDCARD_IMPORT_IN_FACADE":
        return "Replace the wildcard import with explicit imports after import tests confirm the public contract."
    if code == "FACADE_WITHOUT_ALL":
        return "Add an explicit __all__ that lists only intended facade exports."
    if code == "UNBOUND_ALL_EXPORT":
        return "Remove the stale export or bind it from the canonical owner."
    if code == "DYNAMIC_ALL_EXPORT":
        return "Inspect callers and replace dynamic __all__ only after deciding the canonical public surface."
    if code == "DUPLICATE_PUBLIC_SYMBOL":
        return "Choose the canonical owner before changing imports or public exports."
    if code == "BEHAVIOR_DEFINED_IN_FACADE":
        return "Move behavior to an owner module and keep a compatibility facade if callers need the old path."
    if code == "RUNTIME_LOGIC_IN_FACADE":
        return "Move runtime logic out of __init__.py and keep the facade side-effect free."
    if classification == DO_NOT_TOUCH:
        return "Repair the underlying read or syntax problem before planning source edits."
    return _CLASSIFICATION_GUIDANCE[classification]


def _required_tests_for(code: str, classification: str) -> tuple[str, ...]:
    """Support required tests for behavior.
    
    Parameters
    ----------
    code : str
        The code value.
    classification : str
        The classification value.
    
    Returns
    -------
    tuple[str, ...]
        The tuple of values.
    """
    
    base = [
        "python -m py_compile <touched_files>",
        "python kanda_reasoner_app\\manage_architecture\\manage_architecture.py --root <PROJECT_ROOT> --validate",
        "python kanda_reasoner_app\\manage_workflows\\manage_workflows.py --root <PROJECT_ROOT> --validate",
    ]
    if classification == REQUIRES_OWNER_DECISION:
        base.insert(0, "Add or update a focused import-contract test for the chosen canonical owner.")
    elif classification == REQUIRES_COMPATIBILITY_FACADE:
        base.insert(0, "Add compatibility import tests for the old facade path and the new owner path.")
    elif classification == SAFE_MECHANICAL_FIX:
        base.insert(0, "Add a focused facade public-surface test before applying the mechanical fix.")
    elif classification == DO_NOT_TOUCH:
        return ("Rerun the shadow conflict audit after the read or syntax issue is repaired.",)
    if code == "DUPLICATE_PUBLIC_SYMBOL":
        base.insert(0, "Search callers of the duplicated symbol before changing ownership.")
    return tuple(base)


def _rollback_plan_for(classification: str) -> str:
    """Support rollback plan for behavior.
    
    Parameters
    ----------
    classification : str
        The classification value.
    
    Returns
    -------
    str
        The string result.
    """
    
    if classification == DO_NOT_TOUCH:
        return "No source change should be produced by this plan item."
    return "Restore the pre-change file backup or reinstall the previous validated bundle if validation fails."


def _classification_counts(items: Iterable[ShadowCorrectionPlanItem]) -> dict[str, int]:
    """Support classification counts behavior.
    
    Parameters
    ----------
    items : Iterable[ShadowCorrectionPlanItem]
        The item values.
    
    Returns
    -------
    dict[str, int]
        The mapped values.
    """
    
    counts = {
        SAFE_MECHANICAL_FIX: 0,
        REQUIRES_OWNER_DECISION: 0,
        REQUIRES_COMPATIBILITY_FACADE: 0,
        DO_NOT_TOUCH: 0,
    }
    for item in items:
        counts[item.classification] = counts.get(item.classification, 0) + 1
    return counts


def _format_summary(counts: dict[str, int], total: int) -> str:
    """Support format summary behavior.
    
    Parameters
    ----------
    counts : dict[str, int]
        The counts value.
    total : int
        The total value.
    
    Returns
    -------
    str
        The string result.
    """
    
    return (
        "Shadow conflict correction plan completed. "
        + "items="
        + str(total)
        + "; safe_mechanical_fix="
        + str(counts.get(SAFE_MECHANICAL_FIX, 0))
        + "; requires_owner_decision="
        + str(counts.get(REQUIRES_OWNER_DECISION, 0))
        + "; requires_compatibility_facade="
        + str(counts.get(REQUIRES_COMPATIBILITY_FACADE, 0))
        + "; do_not_touch="
        + str(counts.get(DO_NOT_TOUCH, 0))
        + "."
    )
