# project-path: kanda_reasoner_app/engineering_diagnostics/__init__.py
"""Public contract for project-specific Engineering Diagnostics history."""

from .baseline import compare_issue_fingerprints
from .bom_adapter import BOM_PRODUCER_ID, build_bom_diagnostic_run
from .collectors import (
    ARCHITECTURE_COLLECTOR_CONTRACT_VERSION,
    ARCHITECTURE_PRODUCER_ID,
    RUFF_COLLECTOR_CONTRACT_VERSION,
    RUFF_PRODUCER_ID,
    ArchitectureCollectionCancelled,
    ArchitectureCollectionError,
    ArchitectureCollectionResult,
    ArchitectureIssueEvidence,
    RuffCollectionCancelled,
    RuffCollectionError,
    RuffCollectionResult,
    SHADOW_COLLECTOR_CONTRACT_VERSION,
    SHADOW_PRODUCER_ID,
    ShadowCollectionCancelled,
    ShadowCollectionError,
    ShadowCollectionResult,
    ShadowIssueEvidence,
    build_architecture_diagnostic_run,
    build_ruff_diagnostic_run,
    build_shadow_diagnostic_run,
    collect_architecture_findings,
    collect_ruff_json,
    collect_shadow_findings,
)
from .collectors.architecture_normalizer import (
    architecture_configuration_fingerprint,
    architecture_scope_fingerprint,
)
from .collectors.ruff_normalizer import (
    ruff_configuration_fingerprint,
    ruff_scope_fingerprint,
)
from .collectors.shadow_normalizer import (
    shadow_configuration_fingerprint,
    shadow_scope_fingerprint,
)
from .enrichment import EngineeringDiagnosticsEnricher
from .enrichment_models import (
    FROZEN_PATH_STATUSES,
    SCOPE_CLASSIFICATIONS,
    DiagnosticFindingEnrichment,
    DiagnosticFrozenPathEnrichment,
    DiagnosticScopeEnrichment,
)
from .owner_enrichment import (
    DiagnosticOwnerSnapshot,
    build_diagnostic_owner_snapshot,
    classify_diagnostic_owner,
)
from .owner_enrichment_models import (
    OWNER_CONFIDENCE_LEVELS,
    OWNER_ENRICHMENT_STATUSES,
    DiagnosticOwnerEnrichment,
)
from .frozen_path_enrichment import (
    DiagnosticFreezeSnapshot,
    build_diagnostic_freeze_snapshot,
    classify_diagnostic_frozen_path,
    related_project_paths_from_evidence,
)
from .grouping import (
    build_deterministic_diagnostic_groups,
    index_diagnostic_groups,
    primary_diagnostic_group,
)
from .grouping_models import (
    DIAGNOSTIC_GROUPING_SCHEMA_VERSION,
    GROUP_CONFIDENCE_LEVELS,
    GROUP_DECISION_ACTIONS,
    GROUP_KINDS,
    GROUP_REVIEW_STATES,
    DiagnosticGroupDecisionRecord,
    DiagnosticGroupRecord,
    DiagnosticManualGroupingState,
)
from .shadow_relational_grouping import (
    build_shadow_relational_diagnostic_groups,
    build_shadow_relational_graph,
)
from .shadow_relational_models import (
    RELATIONAL_EDGE_KINDS,
    RELATIONAL_NODE_KINDS,
    DiagnosticRelationEdge,
    DiagnosticRelationNode,
    DiagnosticRelationalGraph,
)
from .lifecycle import (
    LIFECYCLE_ACTION_RESULT,
    allowed_lifecycle_actions,
    validate_lifecycle_transition,
)
from .lifecycle_models import (
    DIAGNOSTIC_LIFECYCLE_SCHEMA_VERSION,
    LIFECYCLE_ACTIONS,
    LIFECYCLE_STATES,
    LIFECYCLE_TARGET_KINDS,
    DiagnosticLifecycleDecisionRecord,
    DiagnosticLifecycleHead,
    DiagnosticLifecycleState,
    DiagnosticLifecycleTarget,
)
from .remediation import (
    build_diagnostic_remediation_intent,
    build_diagnostic_remediation_intents,
)
from .remediation_models import (
    AI_HYPOTHESIS_LABEL,
    REMEDIATION_ACTION_CLASSES,
    REMEDIATION_FIX_APPLICABILITY,
    REMEDIATION_MECHANICAL_SAFETY,
    REMEDIATION_SEMANTIC_REVIEW,
    REMEDIATION_TRUST_ORDER,
    DiagnosticAiHypothesis,
    DiagnosticRemediationIntent,
    DiagnosticValidationPlan,
)
from .fingerprinting import (
    canonical_json,
    evidence_digest,
    issue_fingerprint,
    normalize_relative_path,
    run_content_digest,
    scan_identity,
)
from .models import (
    BASELINE_STATES,
    DIAGNOSTIC_SCHEMA_VERSION,
    DiagnosticBaselineRecord,
    DiagnosticBoundaryError,
    DiagnosticComparison,
    DiagnosticConflictError,
    DiagnosticFindingInput,
    DiagnosticFindingRecord,
    DiagnosticRunInput,
    DiagnosticRunRecord,
    DiagnosticStateError,
    DiagnosticValidationError,
    EngineeringDiagnosticsError,
)
from .paths import (
    ENGINEERING_DIAGNOSTICS_DATABASE_NAME,
    ENGINEERING_DIAGNOSTICS_SUPPORT_DIR,
    engineering_diagnostics_database_path,
    engineering_diagnostics_support_root,
)
from .rules import (
    ArchitectureRuleProfile,
    RuffRuleProfile,
    architecture_rule_profile,
    ruff_rule_profile,
)
from .store import EngineeringDiagnosticsStore

__all__ = [
    "ARCHITECTURE_COLLECTOR_CONTRACT_VERSION",
    "ARCHITECTURE_PRODUCER_ID",
    "ArchitectureCollectionCancelled",
    "ArchitectureCollectionError",
    "ArchitectureCollectionResult",
    "ArchitectureIssueEvidence",
    "ArchitectureRuleProfile",
    "BASELINE_STATES",
    "BOM_PRODUCER_ID",
    "DIAGNOSTIC_GROUPING_SCHEMA_VERSION",
    "DIAGNOSTIC_LIFECYCLE_SCHEMA_VERSION",
    "DIAGNOSTIC_SCHEMA_VERSION",
    "DiagnosticBaselineRecord",
    "DiagnosticBoundaryError",
    "DiagnosticComparison",
    "DiagnosticConflictError",
    "DiagnosticFindingInput",
    "DiagnosticGroupDecisionRecord",
    "DiagnosticGroupRecord",
    "DiagnosticFindingRecord",
    "DiagnosticFindingEnrichment",
    "DiagnosticOwnerEnrichment",
    "DiagnosticOwnerSnapshot",
    "DiagnosticFreezeSnapshot",
    "DiagnosticFrozenPathEnrichment",
    "DiagnosticScopeEnrichment",
    "DiagnosticManualGroupingState",
    "DiagnosticLifecycleDecisionRecord",
    "DiagnosticLifecycleHead",
    "DiagnosticLifecycleState",
    "DiagnosticLifecycleTarget",
    "DiagnosticRunInput",
    "DiagnosticRunRecord",
    "DiagnosticStateError",
    "DiagnosticValidationError",
    "ENGINEERING_DIAGNOSTICS_DATABASE_NAME",
    "ENGINEERING_DIAGNOSTICS_SUPPORT_DIR",
    "EngineeringDiagnosticsError",
    "EngineeringDiagnosticsEnricher",
    "FROZEN_PATH_STATUSES",
    "GROUP_CONFIDENCE_LEVELS",
    "GROUP_DECISION_ACTIONS",
    "GROUP_KINDS",
    "GROUP_REVIEW_STATES",
    "LIFECYCLE_ACTIONS",
    "LIFECYCLE_ACTION_RESULT",
    "LIFECYCLE_STATES",
    "LIFECYCLE_TARGET_KINDS",
    "OWNER_CONFIDENCE_LEVELS",
    "OWNER_ENRICHMENT_STATUSES",
    "SCOPE_CLASSIFICATIONS",
    "EngineeringDiagnosticsStore",
    "DiagnosticRelationEdge",
    "DiagnosticRelationNode",
    "DiagnosticRelationalGraph",
    "RELATIONAL_EDGE_KINDS",
    "RELATIONAL_NODE_KINDS",
    "SHADOW_COLLECTOR_CONTRACT_VERSION",
    "SHADOW_PRODUCER_ID",
    "ShadowCollectionCancelled",
    "ShadowCollectionError",
    "ShadowCollectionResult",
    "ShadowIssueEvidence",
    "RUFF_COLLECTOR_CONTRACT_VERSION",
    "RUFF_PRODUCER_ID",
    "RuffCollectionCancelled",
    "RuffCollectionError",
    "RuffCollectionResult",
    "RuffRuleProfile",
    "build_diagnostic_remediation_intents",
    "build_diagnostic_remediation_intent",
    "REMEDIATION_TRUST_ORDER",
    "REMEDIATION_SEMANTIC_REVIEW",
    "REMEDIATION_MECHANICAL_SAFETY",
    "REMEDIATION_FIX_APPLICABILITY",
    "REMEDIATION_ACTION_CLASSES",
    "DiagnosticValidationPlan",
    "DiagnosticRemediationIntent",
    "DiagnosticAiHypothesis",
    "AI_HYPOTHESIS_LABEL",
    "allowed_lifecycle_actions",
    "architecture_configuration_fingerprint",
    "architecture_rule_profile",
    "architecture_scope_fingerprint",
    "build_architecture_diagnostic_run",
    "build_deterministic_diagnostic_groups",
    "build_diagnostic_freeze_snapshot",
    "build_diagnostic_owner_snapshot",
    "build_bom_diagnostic_run",
    "build_ruff_diagnostic_run",
    "build_shadow_diagnostic_run",
    "canonical_json",
    "build_shadow_relational_diagnostic_groups",
    "build_shadow_relational_graph",
    "classify_diagnostic_frozen_path",
    "classify_diagnostic_owner",
    "collect_architecture_findings",
    "collect_ruff_json",
    "collect_shadow_findings",
    "compare_issue_fingerprints",
    "engineering_diagnostics_database_path",
    "engineering_diagnostics_support_root",
    "evidence_digest",
    "index_diagnostic_groups",
    "issue_fingerprint",
    "normalize_relative_path",
    "primary_diagnostic_group",
    "related_project_paths_from_evidence",
    "ruff_configuration_fingerprint",
    "ruff_rule_profile",
    "ruff_scope_fingerprint",
    "shadow_configuration_fingerprint",
    "shadow_scope_fingerprint",
    "validate_lifecycle_transition",
    "run_content_digest",
    "scan_identity",
]
