"""Write controlled local-only enrichment to the local-AI JSON.

This module belongs to the Local-AI JSON Enrichment Box.

It reads the canonical complete JSON only for integrity verification and writes
local-only enrichment only into the selected project root's
project_analysis_evidence/json_complete folder.

It never writes to the canonical complete JSON generated by Tab 4.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

from kanda_reasoner_app.live_source_verification import (
    extract_live_source_snippet,
    verify_live_source_path,
)
from kanda_reasoner_app.local_ai_json_working_copy import build_default_paths

DEFAULT_ENRICHMENT_KEY = "local_ai_enrichment"


@dataclass(frozen=True)
class LocalAIJsonEnrichmentResult:
    """Result returned after local-AI JSON enrichment."""

    action: str
    project_root: str
    canonical_json: str
    local_ai_json: str
    canonical_sha256_before: str
    canonical_sha256_after: str
    local_ai_sha256_before: str
    local_ai_sha256_after: str
    canonical_unchanged: bool
    enriched_path_count: int
    verified_ok_count: int
    missing_count: int
    outside_root_count: int
    too_large_count: int
    message: str


def _sha256_file(path: Path) -> str:
    """Return SHA-256 for a file, or an empty string if missing."""
    if not path.exists() or not path.is_file():
        return ""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _resolve_json_paths(
    project_root: str | Path,
    *,
    canonical_relative_path: str | None = None,
    local_ai_relative_path: str | None = None,
) -> tuple[Path, Path, Path]:
    """Resolve and validate canonical/local-AI JSON paths."""
    root = Path(project_root).resolve()
    defaults = build_default_paths(root)
    canonical = (
        defaults.canonical_json
        if canonical_relative_path is None
        else (root / canonical_relative_path).resolve()
    )
    local_ai = (
        defaults.local_ai_json
        if local_ai_relative_path is None
        else (root / local_ai_relative_path).resolve()
    )

    if canonical == local_ai:
        raise ValueError("Canonical and local-AI JSON paths must be different.")

    try:
        canonical.relative_to(root)
        local_ai.relative_to(root)
    except ValueError as exc:
        raise ValueError("JSON paths must remain inside project_root.") from exc

    if not canonical.exists() or not canonical.is_file():
        raise FileNotFoundError("Canonical complete JSON not found: " + str(canonical))

    if not local_ai.exists() or not local_ai.is_file():
        raise FileNotFoundError("Local-AI working JSON not found: " + str(local_ai))

    return root, canonical, local_ai


def _load_json_object(path: Path) -> dict[str, Any]:
    """Load a JSON object with explicit validation."""
    data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
    if not isinstance(data, dict):
        raise ValueError("Expected top-level JSON object: " + str(path))
    return data


def _write_json_atomic(path: Path, data: dict[str, Any]) -> None:
    """Write JSON using a temporary file and atomic replacement."""
    temp_path = path.with_name(path.name + ".tmp_enrich")
    if temp_path.exists():
        temp_path.unlink()

    try:
        temp_path.write_text(
            json.dumps(data, indent=2, sort_keys=True),
            encoding="utf-8",
        )
        temp_path.replace(path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def _build_verification_record(
    project_root: Path,
    candidate_path: str,
    *,
    snippet_anchor: str = "",
    snippet_context_lines: int = 8,
) -> dict[str, Any]:
    """Build one live-source verification record."""
    path_result = verify_live_source_path(project_root, candidate_path)
    record: dict[str, Any] = {
        "requested_path": candidate_path,
        "status": path_result.status,
        "relative_path": path_result.relative_path,
        "resolved_path": path_result.resolved_path,
        "exists": path_result.exists,
        "is_file": path_result.is_file,
        "size_bytes": path_result.size_bytes,
        "mtime_ns": path_result.mtime_ns,
        "sha256": path_result.sha256,
        "message": path_result.message,
    }

    if path_result.status == "ok" and snippet_anchor:
        snippet = extract_live_source_snippet(
            project_root,
            candidate_path,
            anchor=snippet_anchor,
            context_lines=snippet_context_lines,
        )
        record["snippet"] = {
            "status": snippet.status,
            "anchor": snippet.anchor,
            "line_start": snippet.line_start,
            "line_end": snippet.line_end,
            "text": snippet.text,
            "message": snippet.message,
        }

    return record


def _count_status(records: list[dict[str, Any]], status: str) -> int:
    """Count verification records with a status value."""
    return sum(1 for item in records if item.get("status") == status)


def load_local_ai_enrichment(
    project_root: str | Path,
    *,
    canonical_relative_path: str | None = None,
    local_ai_relative_path: str | None = None,
    enrichment_key: str = DEFAULT_ENRICHMENT_KEY,
) -> dict[str, Any]:
    """Load the local-only enrichment section from the local-AI JSON."""
    _root, _canonical, local_ai = _resolve_json_paths(
        project_root,
        canonical_relative_path=canonical_relative_path,
        local_ai_relative_path=local_ai_relative_path,
    )
    data = _load_json_object(local_ai)
    value = data.get(enrichment_key, {})
    if isinstance(value, dict):
        return value
    return {}


def enrich_local_ai_json_with_live_sources(
    project_root: str | Path,
    candidate_paths: Iterable[str],
    *,
    snippet_anchor: str = "",
    snippet_context_lines: int = 8,
    canonical_relative_path: str | None = None,
    local_ai_relative_path: str | None = None,
    enrichment_key: str = DEFAULT_ENRICHMENT_KEY,
) -> LocalAIJsonEnrichmentResult:
    """Write live-source verification metadata to local-AI JSON only."""
    root, canonical, local_ai = _resolve_json_paths(
        project_root,
        canonical_relative_path=canonical_relative_path,
        local_ai_relative_path=local_ai_relative_path,
    )

    canonical_sha_before = _sha256_file(canonical)
    local_sha_before = _sha256_file(local_ai)

    local_data = _load_json_object(local_ai)

    paths = [str(item).strip() for item in candidate_paths if str(item).strip()]
    records = [
        _build_verification_record(
            root,
            item,
            snippet_anchor=snippet_anchor,
            snippet_context_lines=snippet_context_lines,
        )
        for item in paths
    ]

    previous = local_data.get(enrichment_key, {})
    if not isinstance(previous, dict):
        previous = {}

    payload: dict[str, Any] = dict(previous)
    payload["box"] = "Local-AI JSON Enrichment Box"
    payload["last_updated_utc_seconds"] = time.time()
    payload["source_truth_rule"] = (
        "Live source files are final truth for implementation. "
        "Canonical complete JSON remains web-AI export truth."
    )
    payload["canonical_json"] = str(canonical)
    payload["local_ai_json"] = str(local_ai)
    payload["canonical_sha256_at_enrichment"] = canonical_sha_before
    payload["verified_live_sources"] = records

    local_data[enrichment_key] = payload
    _write_json_atomic(local_ai, local_data)

    canonical_sha_after = _sha256_file(canonical)
    local_sha_after = _sha256_file(local_ai)
    canonical_unchanged = canonical_sha_before == canonical_sha_after

    if not canonical_unchanged:
        raise RuntimeError("Canonical complete JSON changed during enrichment.")

    return LocalAIJsonEnrichmentResult(
        action="enriched",
        project_root=str(root),
        canonical_json=str(canonical),
        local_ai_json=str(local_ai),
        canonical_sha256_before=canonical_sha_before,
        canonical_sha256_after=canonical_sha_after,
        local_ai_sha256_before=local_sha_before,
        local_ai_sha256_after=local_sha_after,
        canonical_unchanged=canonical_unchanged,
        enriched_path_count=len(records),
        verified_ok_count=_count_status(records, "ok"),
        missing_count=_count_status(records, "missing"),
        outside_root_count=_count_status(records, "outside_project_root"),
        too_large_count=_count_status(records, "too_large"),
        message="Local-AI JSON enriched with live-source verification metadata.",
    )


def _print_result(result: LocalAIJsonEnrichmentResult) -> None:
    """Print a plain text enrichment result."""
    print("LOCAL-AI JSON ENRICHMENT RESULT")
    for key, value in asdict(result).items():
        print(str(key) + ": " + str(value))


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point for local-AI JSON enrichment."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Project root.")
    parser.add_argument(
        "--path",
        action="append",
        required=True,
        help="Project-relative live source path. May be repeated.",
    )
    parser.add_argument(
        "--snippet-anchor",
        default="",
        help="Optional anchor to extract snippets for verified source files.",
    )
    parser.add_argument(
        "--snippet-context-lines",
        type=int,
        default=8,
        help="Snippet context lines around anchor.",
    )
    args = parser.parse_args(argv)

    try:
        result = enrich_local_ai_json_with_live_sources(
            args.project_root,
            args.path,
            snippet_anchor=args.snippet_anchor,
            snippet_context_lines=args.snippet_context_lines,
        )
    except Exception as exc:
        print("LOCAL-AI JSON ENRICHMENT ERROR")
        print(type(exc).__name__ + ": " + str(exc))
        return 1

    _print_result(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
