# project-path: kanda_reasoner_app/reasoner_context_collector/collector_main.py
"""Public facade for the Project Reasoner V10 static collector.

The original implementation is stored in private source parts generated by
Pass 059C. The facade preserves the public import path while keeping this
module below the size threshold.
"""

from __future__ import annotations

import base64
import importlib
from pathlib import Path

_PART_FILES = [
    'collector_main_source_part_1_private_impl.py',
    'collector_main_source_part_2_private_impl.py',
    'collector_main_source_part_3_private_impl.py',
    'collector_main_source_part_4_private_impl.py',
    'collector_main_source_part_5_private_impl.py',
]


def _load_part(helper_path: Path, module_name: str):
    """Load one governed source part through the package import system.

    Normal imports work both from source and from PyInstaller's bundled PYZ.
    The previous file-path loader required loose ``.py`` files beside the
    executable and therefore failed in the packaged Tool.
    """
    del module_name
    helper_module = helper_path.stem
    package_name = f"{__package__}.collector_main_help.{helper_module}"
    try:
        return importlib.import_module(package_name)
    except ImportError as exc:
        raise ImportError(
            "Cannot import bundled collector_main helper part: " + package_name
        ) from exc


def _load_original_source() -> str:
    """Support load original source behavior.
    
    Returns
    -------
    str
        The string result.
    """
    
    helper_dir = Path(__file__).resolve().parent / "collector_main_help"
    encoded_parts = []
    for index, filename in enumerate(_PART_FILES, start=1):
        module = _load_part(
            helper_dir / filename,
            f"{__name__}._collector_main_source_part_{index}",
        )
        encoded_parts.append(getattr(module, f"_ENCODED_SOURCE_PART_{index}"))
    source_bytes = base64.b64decode("".join(encoded_parts).encode("ascii"))
    return source_bytes.decode("utf-8-sig")


_ORIGINAL_SOURCE = _load_original_source()
exec(compile(_ORIGINAL_SOURCE, str(Path(__file__).resolve()), "exec"), globals(), globals())
