# project-path: kanda_reasoner_app/reasoner_context_collector/collector_main.py
"""Public facade for the Project Reasoner V10 static collector.

The original implementation is stored in private source parts generated by
Pass 059C. The facade preserves the public import path while keeping this
module below the size threshold.
"""

from __future__ import annotations

import base64
import importlib.util
from pathlib import Path

_PART_FILES = [
    'collector_main_source_part_1_private_impl.py',
    'collector_main_source_part_2_private_impl.py',
    'collector_main_source_part_3_private_impl.py',
    'collector_main_source_part_4_private_impl.py',
    'collector_main_source_part_5_private_impl.py',
]


def _load_part(helper_path: Path, module_name: str):
    """Support load part behavior.
    
    Parameters
    ----------
    helper_path : Path
        The helper path value.
    module_name : str
        The module name value.
    """
    
    spec = importlib.util.spec_from_file_location(module_name, helper_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load collector_main helper part: {helper_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_original_source() -> str:
    """Support load original source behavior.
    
    Returns
    -------
    str
        The string result.
    """
    
    helper_dir = Path(__file__).resolve().parent / "collector_main_help"
    encoded_parts = []
    for index, filename in enumerate(_PART_FILES, start=1):
        module = _load_part(
            helper_dir / filename,
            f"{__name__}._collector_main_source_part_{index}",
        )
        encoded_parts.append(getattr(module, f"_ENCODED_SOURCE_PART_{index}"))
    source_bytes = base64.b64decode("".join(encoded_parts).encode("ascii"))
    return source_bytes.decode("utf-8-sig")


_ORIGINAL_SOURCE = _load_original_source()
exec(compile(_ORIGINAL_SOURCE, str(Path(__file__).resolve()), "exec"), globals(), globals())
