"""Private retrieve_symbols implementation for symbol retrieval.

Generated by Pass 050F.
"""

from __future__ import annotations

import re
from kanda_reasoner_app.reasoner_engine.v10_models import SymbolEvidenceItem
from kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.query_intents import (
    detect_query_intents,
    is_runtime_heavy_question,
)
from kanda_reasoner_app.reasoner_engine.reasoner_retriever_help.query_text import (
    file_name_from_path,
    is_allowed_project_path,
    is_auxiliary_ui_path,
    norm_text,
    tokenize_query,
)

from .symbol_retrieval_evidence_private_impl import _build_symbol_evidence_impl

__all__ = []

def _retrieve_symbols_impl(retriever, question: str, limit: int) -> list[SymbolEvidenceItem]:
    q = norm_text(question)
    tokens = tokenize_query(q)
    intents = detect_query_intents(q)
    owner_locator_target = ''
    owner_locator_prefixes = ['which symbol owns', 'what symbol owns', 'which symbol handles', 'what symbol handles', 'which method owns', 'what method owns', 'which function owns', 'what function owns', 'which symbol directly calls']
    for _prefix in owner_locator_prefixes:
        if q.startswith(_prefix):
            owner_locator_target = q[len(_prefix):].strip().rstrip(' ?.').strip()
            if owner_locator_target.startswith('the '):
                owner_locator_target = owner_locator_target[4:]
            break
    explanation_heavy = intents['explanatory'] or intents['code_localized_explanation'] or intents['explain_chain']
    is_runtime_question = intents['runtime_heavy']
    question_file_names = set(re.findall('[a-zA-Z0-9_\\-]+\\.py', q))
    scored: list[SymbolEvidenceItem] = []
    exact_symbol_targets = [token for token in tokens if ('_' in token or '.' in token) and len(token) >= 6]
    for symbol_name, detail in retriever.idx.symbol_details.items():
        path = detail['file']
        if not is_allowed_project_path(path):
            continue
        record = detail['record']
        symbol_name_norm = norm_text(symbol_name)
        blob = symbol_name_norm
        docstring = norm_text(record.get('docstring', ''))
        calls_blob = ''
        if detail['kind'] in ('function', 'method'):
            calls_blob = norm_text(' '.join([c.get('call_name', '') for c in record.get('calls', [])]))
        haystack = ' '.join([blob, docstring, calls_blob])
        runtime_signal_blob_parts: list[str] = []
        for item in retriever.idx.runtime_signal_connections:
            if not isinstance(item, dict):
                continue
            source_file = str(item.get('source_file', '')).strip()
            if source_file != path:
                continue
            runtime_signal_blob_parts.append(str(item.get('sender_name', '')))
            runtime_signal_blob_parts.append(str(item.get('signal_name', '')))
            runtime_signal_blob_parts.append(str(item.get('slot_name', '')))
            runtime_signal_blob_parts.append(str(item.get('receiver_name', '')))
        haystack = ' '.join([haystack, norm_text(' '.join(runtime_signal_blob_parts))])
        base_name = file_name_from_path(path)
        normalized_path = path.replace('\\', '/').lower()
        last_symbol_part = symbol_name_norm.split('.')[-1]
        call_count = len(record.get('calls', [])) if isinstance(record, dict) else 0
        score = 0
        reasons: list[str] = []
        if base_name and base_name in q:
            score += 30
            reasons.append('symbol-file-match')
        for file_name in question_file_names:
            if base_name == file_name.lower():
                score += 30
                reasons.append('symbol-question-file-match')
        if symbol_name_norm and symbol_name_norm in q:
            score += 120
            reasons.append('exact-symbol-match')
        if last_symbol_part and last_symbol_part in q:
            score += 80
            reasons.append('exact-symbol-tail-match')
        for target in exact_symbol_targets:
            if not target:
                continue
            if symbol_name_norm == target:
                score += 500
                reasons.append('identifier-exact-symbol-match:' + target)
            elif last_symbol_part == target:
                score += 420
                reasons.append('identifier-exact-tail-match:' + target)
            elif symbol_name_norm.endswith('.' + target):
                score += 380
                reasons.append('identifier-qualified-tail-match:' + target)
        if owner_locator_target:
            if symbol_name_norm == owner_locator_target or last_symbol_part == owner_locator_target:
                score += 1000
                reasons.append('exact-owner-target-match')
            elif owner_locator_target in symbol_name_norm:
                score += 220
                reasons.append('owner-target-substring-match')
        for token in tokens:
            if token in haystack:
                score += 4
                reasons.append('symbol-token:' + token)
        if intents['explicit_call_chain'] and 'retriever.v.main_window.show' in calls_blob:
            score += 220
            reasons.append('symbol-exact-call-chain-match')
        if intents['main_window_show']:
            if 'retriever.v.main_window.show' in calls_blob:
                score += 260
                reasons.append('main-window-show-call-boost')
            if 'build_and_show' in symbol_name_norm:
                score += 220
                reasons.append('main-window-show-responsibility-boost')
            generic_symbol_parts = {'show', 'hide', 'refresh', 'data'}
            if last_symbol_part in generic_symbol_parts:
                score -= 140
                reasons.append('generic-main-window-show-penalty')
            if any((term in normalized_path for term in ['main_window', 'viewer', 'launcher'])):
                score += 40
                reasons.append('main-window-show-path-boost')
        if intents['qtimer_showmaximized']:
            if 'qtimer.singleshot' in calls_blob and 'retriever.v.main_window.showmaximized' in calls_blob:
                score += 320
                reasons.append('qtimer-showmaximized-exact-call-boost')
            if 'showmaximized' in calls_blob and 'qtimer.singleshot' not in calls_blob:
                score -= 180
                reasons.append('direct-showmaximized-without-qtimer-penalty')
            if any((term in normalized_path for term in ['main_window', 'viewer', 'launcher'])):
                score += 35
                reasons.append('qtimer-showmaximized-path-boost')
        if intents['where_is']:
            if symbol_name_norm in q:
                score += 220
                reasons.append('where-is-exact-symbol-definition-boost')
            elif last_symbol_part and last_symbol_part in q:
                score += 120
                reasons.append('where-is-symbol-tail-definition-boost')
        if intents['which_calls']:
            if calls_blob:
                score += 20
                reasons.append('which-calls-symbol-has-calls')
            if any((token in calls_blob for token in tokens)):
                score += 160
                reasons.append('which-calls-symbol-call-boost')
            if not calls_blob:
                score -= 50
                reasons.append('which-calls-symbol-no-calls-penalty')
        if intents['explain_chain']:
            orchestration_markers = {'main', 'run', 'build', 'build_and_show', 'display', 'launch'}
            if last_symbol_part in orchestration_markers or 'build_and_show' in symbol_name_norm:
                score += 120
                reasons.append('explain-chain-symbol-orchestrator-boost')
            if any((term in normalized_path for term in ['main_window', 'interface_manager', 'builder', 'launcher', 'main'])):
                score += 30
                reasons.append('explain-chain-symbol-path-boost')
        call_site_builder_query = 'call site' in q or 'constructs' in q or 'top and upper navigation' in q or ('navigation bars' in q) or ('notebook tabs' in q)
        asks_for_navbar_builder = 'navbarbuilder' in q or 'nav bar builder' in q or 'build_top' in q or ('build_upper' in q)
        asks_for_notebook_builder = 'notebookbuilder' in q or 'notebook builder' in q or 'notebook tabs' in q or ('.build' in q)
        reset_cleanup_query = 'reset' in q or 'cleanup' in q or 'snapshot' in q or ('close' in q) or retriever._question_has_profile_alias(q, 'reset_cleanup')
        close_action_query = 'close action' in q or 'close button' in q or 'on_close_clicked' in q or ('close' in q and 'action' in q) or ('close' in q and 'triggered' in q) or ('close' in q and 'clicked' in q)
        reset_runtime_query = is_runtime_heavy_question(q) and ('reset' in q or 'close' in q or 'disconnect' in q or ('timer' in q) or ('signal' in q))
        if call_site_builder_query:
            if 'eegmainwindowbuilder.build_and_show' in symbol_name_norm:
                score += 260
                reasons.append('call-site-build-and-show-symbol-boost')
            if 'eegmainwindowbuilder' in symbol_name_norm and 'build_and_show' in haystack:
                score += 180
                reasons.append('call-site-main-window-builder-symbol-boost')
            if asks_for_navbar_builder and ('navbarbuilder' in symbol_name_norm or 'build_top' in symbol_name_norm or 'build_upper' in symbol_name_norm):
                score += 160
                reasons.append('navbar-builder-symbol-boost')
            if asks_for_notebook_builder and ('notebookbuilder' in symbol_name_norm or 'notebookbuilder.build' in symbol_name_norm):
                score += 160
                reasons.append('notebook-builder-symbol-boost')
        if retriever._question_has_profile_alias(q, 'topomap_explanation') or intents['topomap_explanation']:
            topomap_implementation_query = any((term in q for term in ['implement', 'implements', 'implemented', 'implementation', 'creating', 'updating', 'participate in creating', 'participate in updating', 'modules participate', 'which code implements', 'which modules participate']))
            if 'topomap' in haystack or 'topomap' in symbol_name_norm or retriever._text_has_profile_alias(haystack, 'topomap'):
                score += 240
                reasons.append('symbol-topomap-explanation-core-boost')
            if 'amplitude_map' in haystack or any((term in haystack for term in retriever._profile_alias_terms('topomap_symbol_terms'))):
                score += 140
                reasons.append('symbol-topomap-explanation-amplitude-map-boost')
            if any((marker in haystack for marker in ['draw', 'render', 'renderer', 'plot', 'topography', 'topographic'])) or any((term in haystack for term in retriever._profile_alias_terms('topomap_symbol_terms'))):
                score += 140
                reasons.append('symbol-topomap-explanation-render-boost')
            if any((term in symbol_name_norm for term in retriever._profile_alias_terms('topomap_symbol_terms'))):
                score += 100
                reasons.append('symbol-topomap-explanation-name-boost')
            if any((owner_path in normalized_path for owner_path in retriever._profile_owner_paths('topomap_owner_paths'))):
                score += 60
                reasons.append('symbol-topomap-explanation-path-boost')
            if topomap_implementation_query:
                if any((term in symbol_name_norm for term in retriever._profile_alias_terms('topomap_symbol_terms'))):
                    score += 180
                    reasons.append('symbol-topomap-implementation-symbol-boost')
                if any((owner_path in normalized_path for owner_path in retriever._profile_owner_paths('topomap_owner_paths'))):
                    score += 120
                    reasons.append('symbol-topomap-implementation-path-boost')
            if 'statistics' in normalized_path:
                score -= 100
                reasons.append('symbol-topomap-explanation-noise-penalty')
        if reset_cleanup_query:
            if any((term in symbol_name_norm for term in retriever._profile_alias_terms('reset_cleanup_symbol_terms'))):
                score += 200
                reasons.append('symbol-reset-cleanup-symbol-boost')
            if any((owner_path in normalized_path for owner_path in retriever._profile_owner_paths('reset_cleanup_owner_paths'))):
                score += 120
                reasons.append('symbol-reset-cleanup-path-boost')
            if retriever._text_has_profile_alias(symbol_name_norm, 'reset_cleanup'):
                score += 80
                reasons.append('symbol-reset-cleanup-alias-boost')
        if close_action_query:
            if 'on_close_clicked' in symbol_name_norm:
                score += 320
                reasons.append('close-action-handler-boost')
            if 'eeg_visu_reset_snpsht' in symbol_name_norm:
                score += 300
                reasons.append('close-action-reset-function-boost')
            if 'reset_to_initial_eeg_state' in symbol_name_norm:
                score += 180
                reasons.append('close-action-downstream-reset-boost')
            if normalized_path.startswith('shell/viewer/'):
                score += 80
                reasons.append('close-action-viewer-path-boost')
            if normalized_path.startswith('core/snapshot/'):
                score += 70
                reasons.append('close-action-snapshot-path-boost')
        if reset_runtime_query:
            unrelated_disconnect_symbol = 'disconnect' in symbol_name_norm or 'detach' in symbol_name_norm
            core_reset_runtime_symbol = 'on_close_clicked' in symbol_name_norm or 'eeg_visu_reset_snpsht' in symbol_name_norm or 'reset_to_initial_eeg_state' in symbol_name_norm or ('timeline_moved' in symbol_name_norm) or ('plot_timer' in symbol_name_norm)
            core_reset_runtime_path = normalized_path.startswith('shell/viewer/') or normalized_path.startswith('core/snapshot/')
            if unrelated_disconnect_symbol and (not (core_reset_runtime_symbol or core_reset_runtime_path)):
                score -= 220
                reasons.append('reset-runtime-unrelated-disconnect-penalty')
        if reset_runtime_query:
            asks_amplitude_map = 'amplitude map' in q or 'amplitude-map' in q or 'amp map' in q or ('topomap' in q)
            amplitude_map_signal_symbol = 'amplitude_map' in symbol_name_norm or 'on_eeg_loaded' in symbol_name_norm or 'disconnect_signals' in symbol_name_norm or ('ensure_amplitude_map_signal_connected' in symbol_name_norm)
            amplitude_map_signal_path = 'amplitude_map' in normalized_path or 'eeg_amplitude_map_initializer.py' in normalized_path
            if (amplitude_map_signal_symbol or amplitude_map_signal_path) and (not asks_amplitude_map):
                score -= 180
                reasons.append('reset-runtime-amplitude-map-side-branch-penalty')
        if intents['explicit_call_chain']:
            generic_symbol_parts = {'show', 'hide', 'refresh', 'data'}
            if last_symbol_part in generic_symbol_parts:
                score -= 120
                reasons.append('generic-show-penalty')
            if any((term in normalized_path for term in ['main_window', 'viewer', 'launcher'])):
                score += 30
                reasons.append('symbol-ui-callchain-path-boost')
        if intents['startup']:
            startup_symbol_markers = ['main', 'show', 'showmaximized', 'qapplication', 'exec', 'run', 'build', 'window', 'mainwindow']
            if any((marker in haystack for marker in startup_symbol_markers)):
                score += 15
                reasons.append('symbol-startup-boost')
            if is_auxiliary_ui_path(path):
                score -= 10
                reasons.append('symbol-startup-auxiliary-penalty')
            if any((term in normalized_path for term in ['main_window', 'interface_manager', 'builder', 'launcher', 'main'])):
                score += 10
                reasons.append('symbol-startup-path-boost')
        if explanation_heavy:
            if call_count > 0:
                score += min(40, call_count * 4)
                reasons.append('explanation-symbol-calls-boost')
            if docstring:
                score += 14
                reasons.append('explanation-symbol-docstring-boost')
            if any((marker in symbol_name_norm for marker in ['build', 'init', 'initialize', 'connect', 'load', 'show', 'update', 'refresh', 'render', 'plot', 'draw', 'attach', 'create', 'emit'])):
                score += 56
                reasons.append('explanation-symbol-orchestrator-name-boost')
            if last_symbol_part.startswith('on_'):
                score += 48
                reasons.append('explanation-symbol-handler-boost')
            if any((term in normalized_path for term in ['builder', 'launcher', 'initializer', 'manager', 'controller', 'runner', 'viewer', 'main_window'])):
                score += 28
                reasons.append('explanation-symbol-path-role-boost')
            if detail['kind'] in ('function', 'method'):
                score += 12
                reasons.append('explanation-symbol-executable-boost')
        if is_runtime_question:
            if last_symbol_part in {'on_apply_clicked', 'on_text_changed', 'on_close_clicked'}:
                score += 220
                reasons.append('runtime-symbol-anchor-boost')
            if any((marker in symbol_name_norm for marker in ['runtime_runner_probe_apply_button', 'runtime_runner_probe_line_edit', 'runtime_runner_probe_close_button'])):
                score += 180
                reasons.append('runtime-symbol-probe-anchor-boost')
        if score <= 0:
            continue
        scored.append(SymbolEvidenceItem(evidence_id='', score=score, symbol_name=symbol_name, kind=detail['kind'], path=path, line=detail['line'], reason=', '.join(sorted(set(reasons))), detail=retriever._build_symbol_evidence(symbol_name)))
    scored.sort(key=lambda item: (-item.score, item.symbol_name, item.path))
    scored = scored[:limit]
    reindexed: list[SymbolEvidenceItem] = []
    for idx, item in enumerate(scored, start=1):
        reindexed.append(SymbolEvidenceItem(evidence_id='S' + str(idx).zfill(2), score=item.score, symbol_name=item.symbol_name, kind=item.kind, path=item.path, line=item.line, reason=item.reason, detail=item.detail))
    return reindexed
