# project-path: kanda_reasoner_app/reasoner_engine/reasoner_retriever_help/symbol_retrieval_evidence_private_impl.py
"""Private build_symbol_evidence implementation for symbol retrieval.

Generated by Pass 050F.
"""

from __future__ import annotations

import re


__all__ = []

def _build_symbol_evidence_impl(retriever, symbol_name: str) -> str:
    """Support build symbol evidence impl behavior.
    
    Parameters
    ----------
    retriever : object
        The retriever value.
    symbol_name : str
        The symbol name value.
    
    Returns
    -------
    str
        The string result.
    """
    
    detail = retriever.idx.symbol_details[symbol_name]
    path = detail['file']
    line = detail['line']
    kind = detail['kind']
    record = detail['record']
    lines: list[str] = []
    lines.append('Symbol: ' + symbol_name)
    lines.append('Kind: ' + kind)
    lines.append('Location: ' + path + ':' + str(line))
    if record.get('docstring'):
        docstring = re.sub('\\s+', ' ', str(record.get('docstring', '')).strip())
        lines.append('Docstring: ' + docstring[:500])
    if kind in ('function', 'method'):
        calls = [c.get('call_name', '') for c in record.get('calls', [])[:20]]
        if calls:
            lines.append('Calls: ' + ' | '.join(calls))
    return '\n'.join(lines)
