# project-path: kanda_reasoner_app/manage_workflows/manage_workflows_help/workflow_generation.py
"""Own workflow manifest and WORKFLOWS.md generation."""

from __future__ import annotations

import argparse
import contextlib
import difflib
import fnmatch
import importlib.util
import io
import json
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from .workflow_constants import (
    MANAGED_BY,
    WORKFLOWS_DOC_NAME,
    WORKFLOW_MANIFEST_NAME,
)
from .workflow_io import (
    read_text,
    should_generate_json_manifest,
    should_generate_workflows_doc,
    utc_now_iso,
)

__all__ = [
    "collect_generated_outputs",
    "generate_manifest",
    "generate_workflows_md",
    "load_manifest_or_default",
]

def generate_manifest(root: Path, discovered: dict[str, Any]) -> dict[str, Any]:
    """Support generate manifest behavior.
    
    Parameters
    ----------
    root : Path
        The root path.
    discovered : dict[str, Any]
        The discovered value.
    
    Returns
    -------
    dict[str, Any]
        The mapped values.
    """
    
    default_test_dir = discovered["test_dirs"][0] if discovered["test_dirs"] else "tests"

    return {
        "managed_by": MANAGED_BY,
        "version": 1,
        "generated_at_utc": utc_now_iso(),
        "project_root": str(root),
        "discovered": {
            "python_file_count": discovered["python_file_count"],
            "package_roots": discovered["package_roots"],
            "entry_files": discovered["entry_files"],
            "gui_files": discovered["gui_files"],
            "test_dirs": discovered["test_dirs"],
            "pytest_files": discovered["pytest_files"],
        },
        "workflows": {
            "tests": {
                "enabled": True,
                "runner": "auto",
                "pytest_args": ["-q"],
                "unittest_start_dir": default_test_dir,
                "timeout_seconds": 900,
            },
            "runtime_smoke": {
                "enabled": True,
                "commands": [],
                "note": (
                    "Add commands that exercise real entrypoints or runtime "
                    "flows. This category cannot be inferred safely."
                ),
            },
            "business_checks": {
                "enabled": True,
                "commands": [],
                "note": (
                    "Add domain-specific checks here. Business correctness "
                    "cannot be inferred generically."
                ),
            },
            "gui_workflows": {
                "enabled": True,
                "commands": [],
                "headless_env": {
                    "QT_QPA_PLATFORM": "offscreen",
                },
                "note": (
                    "Add GUI smoke-test commands here. The scanner only "
                    "discovers probable GUI files."
                ),
            },
            "integration": {
                "enabled": True,
                "commands": [],
                "note": "Add cross-module or external-system integration checks.",
            },
            "performance": {
                "enabled": True,
                "commands": [],
                "note": (
                    "Add performance commands with max_seconds thresholds. "
                    "Performance budgets are project-specific."
                ),
            },
            "imports": {
                "enabled": True,
                "module_limit": 25,
                "timeout_seconds": 20,
                "include_modules": [],
                "exclude_patterns": [
                    "*.tests*",
                    "*.test*",
                    "*_gui",
                    "*gui*",
                    "*window*",
                    "*dialog*",
                    "*widget*",
                    "*__main__",
                ],
            },
        },
    }

def generate_workflows_md(manifest: dict[str, Any]) -> str:
    """Support generate workflows md behavior.
    
    Parameters
    ----------
    manifest : dict[str, Any]
        The manifest value.
    
    Returns
    -------
    str
        The string result.
    """
    
    discovered = manifest["discovered"]
    lines: list[str] = [
        "# WORKFLOWS",
        "",
        "> Generated by manage_workflows.py.",
        "",
        "This file describes how dynamic validation is configured for the project.",
        "",
        "## What this tool validates",
        "",
        "- Actual runtime behavior via configured smoke commands.",
        "- Business correctness via configured domain commands.",
        "- GUI workflows via configured GUI commands.",
        "- Integration behavior via configured integration commands.",
        "- Test pass/fail via pytest or unittest.",
        "- Performance via configured commands and optional thresholds.",
        "- Import-time side effects via isolated import probes.",
        "",
        "## Discovered project signals",
        "",
        f"- Python files: {discovered['python_file_count']}",
        f"- Package roots: {', '.join(discovered['package_roots']) or '(none)'}",
        f"- Entry files: {', '.join(discovered['entry_files']) or '(none)'}",
        f"- GUI files: {', '.join(discovered['gui_files']) or '(none)'}",
        f"- Test dirs: {', '.join(discovered['test_dirs']) or '(none)'}",
        f"- Pytest files: {', '.join(discovered['pytest_files']) or '(none)'}",
        "",
        "## Manifest ownership",
        "",
        f"- Canonical machine-readable file: `{WORKFLOW_MANIFEST_NAME}`",
        f"- Managed by: `{manifest['managed_by']}`",
        "",
        "## Command specification",
        "",
        "Each workflow command can be either:",
        "",
        "- a string, executed with the platform shell, or",
        "- an object with fields like:",
        "",
        "```json",
        "{",
        '  "name": "GUI smoke",',
        '  "args": ["{python}", "-m", "pytest", "-q", "tests/gui"],',
        '  "cwd": "{root}",',
        '  "env": {"QT_QPA_PLATFORM": "offscreen"},',
        '  "timeout_seconds": 120,',
        '  "expect_exit_code": 0,',
        '  "max_seconds": 10.0',
        "}",
        "```",
        "",
        "Supported placeholders:",
        "",
        "- `{root}` => selected project root",
        "- `{python}` => current Python executable",
        "",
        "## Recommended flow",
        "",
        "1. Run `python manage_workflows.py --root <project> --write` once.",
        "2. Fill in the command lists inside `workflow_manifest.json`.",
        "3. Run `python manage_workflows.py --root <project> --validate`.",
        "",
    ]
    return "\n".join(lines) + "\n"

def collect_generated_outputs(root: Path, manifest: dict[str, Any]) -> dict[Path, str]:
    """Support collect generated outputs behavior.
    
    Parameters
    ----------
    root : Path
        The root path.
    manifest : dict[str, Any]
        The manifest value.
    
    Returns
    -------
    dict[Path, str]
        The mapped values.
    """
    
    outputs: dict[Path, str] = {}
    manifest_path = root / WORKFLOW_MANIFEST_NAME
    doc_path = root / WORKFLOWS_DOC_NAME

    if should_generate_json_manifest(manifest_path):
        outputs[manifest_path] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    if should_generate_workflows_doc(doc_path):
        outputs[doc_path] = generate_workflows_md(manifest)

    return outputs

def load_manifest_or_default(root: Path, discovered: dict[str, Any]) -> tuple[dict[str, Any], bool]:
    """Load the manifest or default.
    
    Parameters
    ----------
    root : Path
        The root path.
    discovered : dict[str, Any]
        The discovered value.
    
    Returns
    -------
    tuple[dict[str, Any], bool]
        The tuple of values.
    """
    
    path = root / WORKFLOW_MANIFEST_NAME
    generated = generate_manifest(root, discovered)
    if not path.exists():
        return generated, False

    try:
        loaded = json.loads(read_text(path))
    except Exception as exc:
        loaded = generated
        loaded.setdefault("load_warnings", []).append(
            f"Could not parse {WORKFLOW_MANIFEST_NAME}: {exc}"
        )
        return loaded, False

    if not isinstance(loaded, dict):
        generated.setdefault("load_warnings", []).append(
            f"{WORKFLOW_MANIFEST_NAME} is not a JSON object. Using generated defaults."
        )
        return generated, False

    loaded.setdefault("managed_by", MANAGED_BY)
    loaded["project_root"] = str(root)
    loaded["generated_at_utc"] = utc_now_iso()
    loaded["discovered"] = generated["discovered"]

    default_workflows = generated["workflows"]
    loaded_workflows = loaded.setdefault("workflows", {})
    for key, default_value in default_workflows.items():
        if key not in loaded_workflows or not isinstance(loaded_workflows[key], dict):
            loaded_workflows[key] = default_value
        else:
            merged = dict(default_value)
            merged.update(loaded_workflows[key])
            loaded_workflows[key] = merged

    return loaded, True
