"""Read-order guard helpers for generated startup artifacts."""

from __future__ import annotations

import re

from startup_kernel.constants import (
    STARTUP_ARTIFACT_READ_ORDER_MARKER,
)


__all__ = [
    "make_startup_artifact_read_order_notice",
    "strip_startup_artifact_read_order_block",
    "add_read_order_block",
]

def make_startup_artifact_read_order_notice(artifact_name: str = "") -> str:
    artifact_label = artifact_name or "this startup artifact"
    return f"""# STARTUP DELIVERY READ ORDER - READ tell_AI_read_before_all.md FIRST

You are seeing `{artifact_label}`.

Mandatory reading order for this startup delivery:

```text
1. tell_AI_read_before_all.md - read this file first, before any ZIP contents.
2. first_prompts_to_ai.zip - after step 1, open this ZIP and read 00_START_HERE_FOR_AI.md first, then the numbered startup files in order.
3. prompt_library.zip - keep available, but open it only when startup routing selects a specific prompt_path that is not already inside first_prompts_to_ai.zip.
4. zz_read_only_if_modifying_startup_delivery.md - optional. Read only when modifying startup delivery. If this file is missing, pass and continue normal startup.
```

If you opened this file from inside a ZIP before reading `tell_AI_read_before_all.md`, stop using the ZIP now, read `tell_AI_read_before_all.md`, then resume with the correct order.

This guard is generated by `sync_startup_routing_kernel_pack.py` and must remain at the top of generated startup artifacts.

"""

def strip_startup_artifact_read_order_block(content: str) -> str:
    if not content.startswith("# " + STARTUP_ARTIFACT_READ_ORDER_MARKER):
        return content
    end_phrase = "This guard is generated by `sync_startup_routing_kernel_pack.py` and must remain at the top of generated startup artifacts."
    end_index = content.find(end_phrase)
    if end_index >= 0:
        after = content.find("\n", end_index + len(end_phrase))
        if after >= 0:
            return content[after + 1 :].lstrip()
        return ""
    matches = list(re.finditer("\\n# (?!STARTUP DELIVERY READ ORDER)", content))
    if matches:
        return content[matches[0].start() + 1 :].lstrip()
    return content

def add_read_order_block(content: str, artifact_name: str) -> str:
    body = strip_startup_artifact_read_order_block(content)
    return make_startup_artifact_read_order_notice(artifact_name).rstrip() + "\n\n" + body.lstrip()

