# project-path: kanda_reasoner_app/routing_signal_scorer/__init__.py
"""Diagnostic routing signal scorer for KANDA prompt-call accuracy."""

from .contract import (
    ADVISORY_AUTHORITY,
    ADVISORY_FEATURE_ID,
    AUTHORITY,
    FEATURE_ID,
    PRE_OUTPUT_HOOK,
    SIMILARITY_EXPLAINABILITY_FEATURE_ID,
    SIMILARITY_DECISION_REPORT_FEATURE_ID,
    SIMILARITY_HIGH_THRESHOLD,
    SIMILARITY_PROMOTION_THRESHOLD,
    SIMILARITY_RUNTIME_LITE_AUTHORITY,
    SIMILARITY_RUNTIME_LITE_FEATURE_ID,
    SIMILARITY_THRESHOLD_POLICY_FEATURE_ID,
    SIMILARITY_UI_PREVIEW_ADAPTER_FEATURE_ID,
    SIMILARITY_PROMPT_CONTEXT_PREVIEW_FEATURE_ID,
    SIMILARITY_BOX_SHIELD_FEATURE_ID,
    SIMILARITY_VISIBILITY_THRESHOLD,
    SCHEMA_VERSION,
    SIGNAL_NAMES,
    build_routing_advisory,
    build_similarity_runtime_lite_advisory,
    build_similarity_ui_preview_adapter,
    build_similarity_prompt_context_preview,
    build_similarity_box_shield_status,
    score_routing_signals,
    summarize_advisory,
    summarize_similarity_runtime_lite_advisory,
    render_similarity_ui_preview_text,
    render_similarity_prompt_context_preview_text,
    render_similarity_box_shield_status_text,
    summarize_signal_result,
)

__all__ = [
    "ADVISORY_AUTHORITY",
    "ADVISORY_FEATURE_ID",
    "AUTHORITY",
    "FEATURE_ID",
    "PRE_OUTPUT_HOOK",
    "SIMILARITY_EXPLAINABILITY_FEATURE_ID",
    "SIMILARITY_DECISION_REPORT_FEATURE_ID",
    "SIMILARITY_HIGH_THRESHOLD",
    "SIMILARITY_PROMOTION_THRESHOLD",
    "SIMILARITY_RUNTIME_LITE_AUTHORITY",
    "SIMILARITY_RUNTIME_LITE_FEATURE_ID",
    "SIMILARITY_THRESHOLD_POLICY_FEATURE_ID",
    "SIMILARITY_UI_PREVIEW_ADAPTER_FEATURE_ID",
    "SIMILARITY_PROMPT_CONTEXT_PREVIEW_FEATURE_ID",
    "SIMILARITY_BOX_SHIELD_FEATURE_ID",
    "SIMILARITY_VISIBILITY_THRESHOLD",
    "SCHEMA_VERSION",
    "SIGNAL_NAMES",
    "build_routing_advisory",
    "build_similarity_runtime_lite_advisory",
    "build_similarity_ui_preview_adapter",
    "build_similarity_prompt_context_preview",
    "build_similarity_box_shield_status",
    "score_routing_signals",
    "summarize_advisory",
    "summarize_similarity_runtime_lite_advisory",
    "render_similarity_ui_preview_text",
    "render_similarity_prompt_context_preview_text",
    "render_similarity_box_shield_status_text",
    "summarize_signal_result",
]
