#!/usr/bin/env python3
"""Pre-pass module summarizer for AI-powered docstring generation.

Before the per-symbol AI calls begin for a file, this module makes a single
"understand this module" call to the LLM.  The resulting :class:`ModuleSummary`
is then injected as context into every subsequent class, function, and method
prompt in that file, dramatically improving coherence across all generated
docstrings.

This is a read-only, stateless pass — it never modifies source files.
"""

from __future__ import annotations

import ast
import json
import textwrap
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ai_config import AIConfig


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class InitAttribute:
    """A single ``self.<name> = ...`` assignment found in ``__init__``.

    Parameters
    ----------
    name : str
        Attribute name without the ``self.`` prefix.
    type_hint : str
        Type annotation from the ``__init__`` parameter that feeds this
        attribute, or ``""`` when no annotation is present.
    assigned_from : str
        Source expression being assigned (e.g. ``"path"`` or ``"Path(root)"``),
        truncated to 80 characters.
    """

    name: str
    type_hint: str = ""
    assigned_from: str = ""


@dataclass
class ClassProfile:
    """Static analysis profile of a single class in a module.

    Parameters
    ----------
    name : str
        Simple class name.
    bases : list[str]
        Base class names as unparsed expressions.
    decorators : list[str]
        Decorator names in source order.
    init_params : list[tuple[str, str]]
        ``(param_name, annotation)`` pairs from ``__init__``, excluding
        ``self``/``cls``.
    init_attributes : list[InitAttribute]
        ``self.<attr> = ...`` assignments found in ``__init__``.
    public_methods : list[str]
        Names of public methods (not starting with ``_``).
    private_methods : list[str]
        Names of private methods (starting with ``_``).
    property_names : list[str]
        Names of ``@property`` decorated methods.
    is_abstract : bool
        True when the class inherits from ``ABC`` or uses ``ABCMeta``.
    is_dataclass : bool
        True when decorated with ``@dataclass``.
    lineno : int
        1-based line number of the ``class`` keyword.
    """

    name: str
    bases: list[str] = field(default_factory=list)
    decorators: list[str] = field(default_factory=list)
    init_params: list[tuple[str, str]] = field(default_factory=list)
    init_attributes: list[InitAttribute] = field(default_factory=list)
    public_methods: list[str] = field(default_factory=list)
    private_methods: list[str] = field(default_factory=list)
    property_names: list[str] = field(default_factory=list)
    is_abstract: bool = False
    is_dataclass: bool = False
    lineno: int = 0


@dataclass
class ModuleSummary:
    """Complete understanding of a module produced by the pre-pass.

    Parameters
    ----------
    module_id : str
        Dotted module identifier (e.g. ``"mypackage.utils"``).
    one_liner : str
        A single sentence describing what the module does, generated by the AI
        (or derived heuristically if the AI call fails).
    purpose_paragraph : str
        2–3 sentence expanded description for use as context in per-symbol
        prompts.  May be empty if the AI only produced a one-liner.
    classes : list[ClassProfile]
        Static analysis profiles for every class in the module.
    public_functions : list[str]
        Names of module-level public functions.
    constants : list[str]
        Names of module-level ``UPPER_CASE`` constants.
    ai_generated : bool
        True when the summary came from an LLM call rather than heuristics.
    """

    module_id: str
    one_liner: str
    purpose_paragraph: str = ""
    classes: list[ClassProfile] = field(default_factory=list)
    public_functions: list[str] = field(default_factory=list)
    constants: list[str] = field(default_factory=list)
    ai_generated: bool = False

    @property
    def context_block(self) -> str:
        """Return a compact prose block ready to embed in per-symbol prompts.

        Returns
        -------
        str
            Multi-line string describing module purpose, classes, and exports.
        """
        parts = [f"Module purpose: {self.one_liner}"]
        if self.purpose_paragraph and self.purpose_paragraph != self.one_liner:
            parts.append(self.purpose_paragraph.strip())
        if self.classes:
            names = ", ".join(c.name for c in self.classes[:6])
            parts.append(f"Classes in module: {names}.")
        if self.public_functions:
            names = ", ".join(self.public_functions[:8])
            parts.append(f"Public functions: {names}.")
        return "\n".join(parts)


# ---------------------------------------------------------------------------
# Static AST analysis — no LLM needed
# ---------------------------------------------------------------------------


def _safe_unparse(node: ast.expr | None) -> str:
    if node is None:
        return ""
    try:
        return ast.unparse(node)
    except Exception:
        return ""


def _extract_init_attributes(init_node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[InitAttribute]:
    """Return all ``self.<attr> = <expr>`` assignments found in ``__init__``.

    Parameters
    ----------
    init_node : ast.FunctionDef | ast.AsyncFunctionDef
        The ``__init__`` method AST node.

    Returns
    -------
    list[InitAttribute]
        One entry per unique ``self.<attr>`` assignment.
    """
    seen: set[str] = set()
    attrs: list[InitAttribute] = []

    # Build a quick lookup: param_name -> annotation_text for type resolution.
    param_annotations: dict[str, str] = {}
    for arg in init_node.args.args:
        if arg.arg == "self":
            continue
        if arg.annotation:
            param_annotations[arg.arg] = _safe_unparse(arg.annotation)

    for node in ast.walk(init_node):
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if not (
                isinstance(target, ast.Attribute)
                and isinstance(target.value, ast.Name)
                and target.value.id == "self"
            ):
                continue
            attr_name = target.attr
            if attr_name in seen:
                continue
            seen.add(attr_name)

            # Try to resolve the type from the RHS.
            assigned_src = _safe_unparse(node.value)[:80]
            type_hint = ""
            # If RHS is a bare Name that matches an __init__ param, use its annotation.
            if isinstance(node.value, ast.Name) and node.value.id in param_annotations:
                type_hint = param_annotations[node.value.id]
            # If RHS is a Call, use the function name as a type hint candidate.
            elif isinstance(node.value, ast.Call):
                type_hint = _safe_unparse(node.value.func)

            attrs.append(InitAttribute(
                name=attr_name,
                type_hint=type_hint,
                assigned_from=assigned_src,
            ))

    return attrs


def _extract_annotated_attributes(class_node: ast.ClassDef) -> list[InitAttribute]:
    """Return ``self.<attr>: Type`` annotations from ``__init__`` body.

    This covers the pattern ``self.x: int = 0`` which ``_extract_init_attributes``
    misses because it looks only at plain ``Assign`` nodes.

    Parameters
    ----------
    class_node : ast.ClassDef
        The class AST node to scan.

    Returns
    -------
    list[InitAttribute]
        Annotated attribute assignments.
    """
    attrs: list[InitAttribute] = []
    seen: set[str] = set()

    for node in ast.walk(class_node):
        if not isinstance(node, ast.AnnAssign):
            continue
        target = node.target
        if not (
            isinstance(target, ast.Attribute)
            and isinstance(target.value, ast.Name)
            and target.value.id == "self"
        ):
            continue
        attr_name = target.attr
        if attr_name in seen:
            continue
        seen.add(attr_name)
        type_hint = _safe_unparse(node.annotation)
        assigned_src = _safe_unparse(node.value)[:80] if node.value else ""
        attrs.append(InitAttribute(
            name=attr_name,
            type_hint=type_hint,
            assigned_from=assigned_src,
        ))

    return attrs


def _profile_class(class_node: ast.ClassDef) -> ClassProfile:
    """Build a :class:`ClassProfile` for *class_node* without any LLM call.

    Parameters
    ----------
    class_node : ast.ClassDef
        The class AST node.

    Returns
    -------
    ClassProfile
        Fully populated static analysis profile.
    """
    bases = [_safe_unparse(b) for b in class_node.bases if _safe_unparse(b)]
    dec_names = []
    for dec in class_node.decorator_list:
        if isinstance(dec, ast.Name):
            dec_names.append(dec.id)
        elif isinstance(dec, ast.Attribute):
            dec_names.append(dec.attr)
        else:
            try:
                dec_names.append(ast.unparse(dec))
            except Exception:
                pass

    is_abstract = any(b in {"ABC", "ABCMeta"} for b in bases) or \
                  any("abstract" in b.lower() for b in bases)
    is_dataclass = "dataclass" in dec_names

    init_node: ast.FunctionDef | ast.AsyncFunctionDef | None = None
    public_methods: list[str] = []
    private_methods: list[str] = []
    property_names: list[str] = []

    for node in class_node.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name == "__init__":
            init_node = node
            continue
        method_decs = [
            d.id if isinstance(d, ast.Name) else (d.attr if isinstance(d, ast.Attribute) else "")
            for d in node.decorator_list
        ]
        if "property" in method_decs:
            property_names.append(node.name)
        if node.name.startswith("_"):
            private_methods.append(node.name)
        else:
            public_methods.append(node.name)

    # Collect __init__ params (excluding self/cls).
    init_params: list[tuple[str, str]] = []
    init_attrs: list[InitAttribute] = []
    if init_node is not None:
        for arg in init_node.args.args:
            if arg.arg in {"self", "cls"}:
                continue
            ann = _safe_unparse(arg.annotation) or "object"
            init_params.append((arg.arg, ann))
        init_attrs = _extract_init_attributes(init_node)

    # Merge with annotated attributes (self.x: Type = ...).
    annotated = _extract_annotated_attributes(class_node)
    existing_names = {a.name for a in init_attrs}
    for a in annotated:
        if a.name not in existing_names:
            init_attrs.append(a)
            existing_names.add(a.name)

    return ClassProfile(
        name=class_node.name,
        bases=bases,
        decorators=dec_names,
        init_params=init_params,
        init_attributes=init_attrs,
        public_methods=public_methods,
        private_methods=private_methods,
        property_names=property_names,
        is_abstract=is_abstract,
        is_dataclass=is_dataclass,
        lineno=class_node.lineno,
    )


def _extract_module_structure(tree: ast.Module) -> tuple[list[ClassProfile], list[str], list[str]]:
    """Return (classes, public_functions, constants) from a parsed module.

    Parameters
    ----------
    tree : ast.Module
        Parsed module AST.

    Returns
    -------
    tuple
        ``(classes, public_functions, constants)`` extracted from the module body.
    """
    classes: list[ClassProfile] = []
    public_functions: list[str] = []
    constants: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes.append(_profile_class(node))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                public_functions.append(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    name = target.id
                    if name.isupper() and not name.startswith("_"):
                        constants.append(name)
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name):
                name = node.target.id
                if name.isupper() and not name.startswith("_"):
                    constants.append(name)

    return classes, public_functions, constants


# ---------------------------------------------------------------------------
# Heuristic fallback summary (no LLM)
# ---------------------------------------------------------------------------


def _heuristic_summary(path: Path, module_id: str, tree: ast.Module) -> str:
    """Generate a plain-text module description from the module's structure.

    Parameters
    ----------
    path : Path
        Module file path.
    module_id : str
        Dotted module identifier.
    tree : ast.Module
        Parsed module AST.

    Returns
    -------
    str
        One-line summary string.
    """
    if path.name == "__init__.py":
        pkg = module_id.split(".")[-2] if "." in module_id else module_id
        return f"Package facade for {pkg.replace('_', ' ').lower()}."
    stem = path.stem.replace("_", " ").lower()
    classes, funcs, _ = _extract_module_structure(tree)
    if classes and funcs:
        return (
            f"Provides {stem} utilities including "
            f"{classes[0].name} and {len(funcs)} function(s)."
        )
    if classes:
        names = ", ".join(c.name for c in classes[:3])
        return f"Defines {names} for {stem}."
    if funcs:
        return f"Utilities and helpers for {stem}."
    return f"Utilities and definitions for {stem or path.stem}."


# ---------------------------------------------------------------------------
# LLM prompt for module pre-pass
# ---------------------------------------------------------------------------


def _build_module_summary_prompt(
    path: Path,
    module_id: str,
    source_lines: list[str],
    classes: list[ClassProfile],
    public_functions: list[str],
    constants: list[str],
) -> str:
    """Build the user prompt for the module-level pre-pass AI call.

    Parameters
    ----------
    path : Path
        Module file path.
    module_id : str
        Dotted module identifier.
    source_lines : list[str]
        Raw source lines of the module.
    classes : list[ClassProfile]
        Profiled classes for structural context.
    public_functions : list[str]
        Public function names.
    constants : list[str]
        Module-level constant names.

    Returns
    -------
    str
        Complete user prompt string.
    """
    parts: list[str] = [
        f"MODULE: {module_id}",
        f"FILE: {path.name}",
    ]

    if classes:
        class_lines = []
        for c in classes[:5]:
            bases = f"({', '.join(c.bases)})" if c.bases else ""
            attrs = ", ".join(a.name for a in c.init_attributes[:4])
            attr_note = f" [attrs: {attrs}]" if attrs else ""
            class_lines.append(f"  class {c.name}{bases}{attr_note}")
        parts.append("CLASSES:\n" + "\n".join(class_lines))

    if public_functions:
        parts.append("PUBLIC FUNCTIONS: " + ", ".join(public_functions[:10]))

    if constants:
        parts.append("CONSTANTS: " + ", ".join(constants[:8]))

    # Provide first 50 lines of source as content preview.
    preview = textwrap.dedent("\n".join(source_lines[:50])).strip()
    parts.append("\nSOURCE PREVIEW (first 50 lines):\n```python\n" + preview + "\n```")

    parts.append(
        "\nTask: In 1–3 sentences, describe what this module does and what "
        "problems it solves. Be concrete — name the key classes or functions "
        "if they are central to the module's purpose.\n"
        "Output format: respond with a JSON object with two keys:\n"
        '  "one_liner": one sentence ending with a period.\n'
        '  "paragraph": 1-3 sentences of additional context (may equal one_liner '
        "if nothing useful can be added).\n"
        "Output ONLY the JSON. No prose, no code blocks, no markdown."
    )
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_module_summary(
    path: Path,
    module_id: str,
    tree: ast.Module,
    source_lines: list[str],
    ai_config: "AIConfig | None" = None,
) -> ModuleSummary:
    """Build a :class:`ModuleSummary` for *path*, using AI when available.

    This is the entry point called once per file before per-symbol processing
    begins.  When *ai_config* is ``None`` or the LLM call fails, a heuristic
    summary is returned and ``ai_generated`` will be ``False``.

    Parameters
    ----------
    path : Path
        Filesystem path to the Python module.
    module_id : str
        Dotted module identifier (e.g. ``"mypackage.utils"``).
    tree : ast.Module
        Parsed AST of the module.
    source_lines : list[str]
        Raw lines of the module source file.
    ai_config : AIConfig, optional
        When provided, an LLM call is made for richer context.

    Returns
    -------
    ModuleSummary
        Fully populated summary with class profiles and AI-generated prose.
    """
    classes, public_functions, constants = _extract_module_structure(tree)

    # Always build the heuristic first as the safe fallback.
    heuristic_one_liner = _heuristic_summary(path, module_id, tree)
    base = ModuleSummary(
        module_id=module_id,
        one_liner=heuristic_one_liner,
        classes=classes,
        public_functions=public_functions,
        constants=constants,
        ai_generated=False,
    )

    if ai_config is None:
        return base

    # --- LLM call ---
    prompt = _build_module_summary_prompt(
        path, module_id, source_lines, classes, public_functions, constants
    )
    payload = json.dumps({
        "model": ai_config.model,
        "max_tokens": 256,           # summaries are short
        "temperature": 0.05,         # near-deterministic
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a senior Python architect. "
                    "Analyse the module structure shown and respond ONLY with "
                    "a JSON object containing 'one_liner' and 'paragraph' keys. "
                    "No prose, no markdown, no code blocks."
                ),
            },
            {"role": "user", "content": prompt},
        ],
    }).encode("utf-8")

    endpoint = ai_config.base_url.rstrip("/") + "/chat/completions"
    req = urllib.request.Request(
        endpoint,
        data=payload,
        method="POST",
        headers={"Content-Type": "application/json", "Accept": "application/json"},
    )

    try:
        with urllib.request.urlopen(req, timeout=min(ai_config.timeout_seconds, 20.0)) as resp:
            body = resp.read().decode("utf-8")
        data = json.loads(body)
        raw_text = data["choices"][0]["message"]["content"].strip()

        # Strip accidental markdown fences.
        if raw_text.startswith("```"):
            raw_text = "\n".join(
                line for line in raw_text.splitlines()
                if not line.startswith("```")
            ).strip()

        parsed = json.loads(raw_text)
        one_liner = str(parsed.get("one_liner", "")).strip()
        paragraph = str(parsed.get("paragraph", "")).strip()

        if not one_liner:
            return base

        # Ensure one_liner ends with a period.
        if one_liner and not one_liner.endswith("."):
            one_liner += "."

        return ModuleSummary(
            module_id=module_id,
            one_liner=one_liner,
            purpose_paragraph=paragraph,
            classes=classes,
            public_functions=public_functions,
            constants=constants,
            ai_generated=True,
        )

    except Exception:
        # Any failure (network, parse, key error) → return heuristic silently.
        return base


def get_class_profile(summary: ModuleSummary, class_name: str) -> ClassProfile | None:
    """Look up a :class:`ClassProfile` by name from a :class:`ModuleSummary`.

    Parameters
    ----------
    summary : ModuleSummary
        The module summary containing profiled classes.
    class_name : str
        Simple class name to look up.

    Returns
    -------
    ClassProfile or None
        The matching profile, or ``None`` if not found.
    """
    for c in summary.classes:
        if c.name == class_name:
            return c
    return None
