"""Evidence README and manifest writer for Kanda architecture audits.

This module builds small descriptive files for external architecture audit
folders. It is side-effect free on import: importing it must not create
folders, move files, delete files, scan the source tree, or change existing
audit output behavior.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime
import json
from pathlib import Path
from typing import Iterable

from kanda_reasoner_app.storage_policy.architecture_audit_resolver import (
    ARCHITECTURE_AUDIT_ARTIFACT_SUFFIXES,
    ARCHITECTURE_AUDIT_DOMAIN,
    get_architecture_audit_artifact_path,
    get_project_slug,
)
from kanda_reasoner_app.storage_policy.path_resolver import get_app_root, normalize_path

EVIDENCE_GENERATOR_APP_NAME = "Kanda Reasoner"
EVIDENCE_MANIFEST_FILENAME = "EVIDENCE_MANIFEST.json"
EVIDENCE_README_FILENAME = "EVIDENCE_README.md"
EVIDENCE_MANIFEST_SCHEMA_VERSION = 1
EVIDENCE_DEFAULT_APP_VERSION = "unknown"
EVIDENCE_CURRENT_LABEL = "current"
EVIDENCE_RUN_LABEL = "run"


@dataclass(frozen=True)
class EvidenceManifest:
    """Machine-readable metadata for one architecture audit output folder."""

    schema_version: int
    generated_by_app: str
    generated_by_version: str
    generated_at: str
    source_project_root: str
    source_project_slug: str
    artifact_domain: str
    artifact_list: tuple[str, ...]
    current_or_run: str
    can_regenerate: bool


def _iso_timestamp(value: datetime | None = None) -> str:
    """Return a stable ISO timestamp without microseconds."""
    timestamp = datetime.now() if value is None else value
    return timestamp.replace(microsecond=0).isoformat()


def _normalize_artifact_list(artifact_list: Iterable[str] | None) -> tuple[str, ...]:
    """Return a stable tuple of non-empty artifact names."""
    if artifact_list is None:
        return ()

    normalized: list[str] = []
    for item in artifact_list:
        text = str(item).strip()
        if text:
            normalized.append(text)
    return tuple(normalized)


def get_default_evidence_artifact_names(project_root: str | Path | None = None) -> tuple[str, ...]:
    """Return canonical architecture audit artifact filenames for a project."""
    return tuple(
        get_architecture_audit_artifact_path(project_root, suffix).name
        for suffix in ARCHITECTURE_AUDIT_ARTIFACT_SUFFIXES
    )


def build_evidence_manifest(
    project_root: str | Path | None = None,
    artifact_list: Iterable[str] | None = None,
    generated_by_version: str = EVIDENCE_DEFAULT_APP_VERSION,
    generated_at: datetime | None = None,
    current_or_run: str = EVIDENCE_CURRENT_LABEL,
    artifact_domain: str = ARCHITECTURE_AUDIT_DOMAIN,
    can_regenerate: bool = True,
) -> EvidenceManifest:
    """Build an evidence manifest object without writing it to disk."""
    root = get_app_root() if project_root is None else normalize_path(project_root)
    artifacts = _normalize_artifact_list(artifact_list)
    if not artifacts:
        artifacts = get_default_evidence_artifact_names(root)

    label = str(current_or_run).strip() or EVIDENCE_CURRENT_LABEL

    return EvidenceManifest(
        schema_version=EVIDENCE_MANIFEST_SCHEMA_VERSION,
        generated_by_app=EVIDENCE_GENERATOR_APP_NAME,
        generated_by_version=str(generated_by_version).strip() or EVIDENCE_DEFAULT_APP_VERSION,
        generated_at=_iso_timestamp(generated_at),
        source_project_root=str(root),
        source_project_slug=get_project_slug(root),
        artifact_domain=str(artifact_domain).strip() or ARCHITECTURE_AUDIT_DOMAIN,
        artifact_list=artifacts,
        current_or_run=label,
        can_regenerate=bool(can_regenerate),
    )


def evidence_manifest_to_dict(manifest: EvidenceManifest) -> dict[str, object]:
    """Convert an evidence manifest dataclass to a JSON-friendly dict."""
    data = asdict(manifest)
    data["artifact_list"] = list(manifest.artifact_list)
    return data


def render_evidence_manifest_json(manifest: EvidenceManifest) -> str:
    """Render an evidence manifest as deterministic JSON text."""
    return json.dumps(evidence_manifest_to_dict(manifest), indent=2, sort_keys=True) + "\n"


def render_evidence_readme(manifest: EvidenceManifest) -> str:
    """Render a human-readable README for an architecture audit folder."""
    artifacts = "\n".join(f"- {name}" for name in manifest.artifact_list)
    if not artifacts:
        artifacts = "- No artifacts were listed when this README was generated."

    return (
        "# Kanda Reasoner Architecture Audit Evidence\n\n"
        "This folder contains generated architecture audit evidence.\n\n"
        f"Generated by: {manifest.generated_by_app}\n"
        f"Generator version: {manifest.generated_by_version}\n"
        f"Generated at: {manifest.generated_at}\n"
        f"Source project root: {manifest.source_project_root}\n"
        f"Source project slug: {manifest.source_project_slug}\n"
        f"Artifact domain: {manifest.artifact_domain}\n"
        f"Output kind: {manifest.current_or_run}\n"
        f"Can regenerate: {str(manifest.can_regenerate).lower()}\n\n"
        "## Artifacts\n\n"
        f"{artifacts}\n\n"
        "## Notes\n\n"
        "These files are generated evidence, not application source. "
        "They can be regenerated by running the Kanda Reasoner audit/export "
        "workflow for the same source project. Do not place this folder inside "
        "the source tree unless explicitly requested for a special workflow.\n"
    )


def get_evidence_manifest_path(output_root: str | Path) -> Path:
    """Return the manifest path for an explicit evidence output root."""
    return normalize_path(output_root) / EVIDENCE_MANIFEST_FILENAME


def get_evidence_readme_path(output_root: str | Path) -> Path:
    """Return the README path for an explicit evidence output root."""
    return normalize_path(output_root) / EVIDENCE_README_FILENAME


def write_evidence_manifest(
    output_root: str | Path,
    manifest: EvidenceManifest,
    overwrite: bool = True,
) -> Path:
    """Explicitly write an evidence manifest to an output root."""
    path = get_evidence_manifest_path(output_root)
    if path.exists() and not overwrite:
        raise FileExistsError(f"Evidence manifest already exists: {path}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_evidence_manifest_json(manifest), encoding="utf-8")
    return path


def write_evidence_readme(
    output_root: str | Path,
    manifest: EvidenceManifest,
    overwrite: bool = True,
) -> Path:
    """Explicitly write an evidence README to an output root."""
    path = get_evidence_readme_path(output_root)
    if path.exists() and not overwrite:
        raise FileExistsError(f"Evidence README already exists: {path}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_evidence_readme(manifest), encoding="utf-8")
    return path


__all__ = [
    "EVIDENCE_CURRENT_LABEL",
    "EVIDENCE_DEFAULT_APP_VERSION",
    "EVIDENCE_GENERATOR_APP_NAME",
    "EVIDENCE_MANIFEST_FILENAME",
    "EVIDENCE_MANIFEST_SCHEMA_VERSION",
    "EVIDENCE_README_FILENAME",
    "EVIDENCE_RUN_LABEL",
    "EvidenceManifest",
    "build_evidence_manifest",
    "evidence_manifest_to_dict",
    "get_default_evidence_artifact_names",
    "get_evidence_manifest_path",
    "get_evidence_readme_path",
    "render_evidence_manifest_json",
    "render_evidence_readme",
    "write_evidence_manifest",
    "write_evidence_readme",
]
