"""Report-only sensitive value scan gate for Kanda Reasoner storage policy.

This module detects likely secrets and credential material in files. It is
report-only: importing or scanning never moves files, deletes files, creates
folders, writes logs, or prints sensitive values. Summaries must redact matched
content and show only file paths, line numbers, and pattern names.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import re

from kanda_reasoner_app.storage_policy.path_resolver import normalize_path

SECRET_SCAN_ACTION = "report_only"
SECRET_SCAN_SEVERITY_HIGH = "high"
SECRET_SCAN_SEVERITY_MEDIUM = "medium"
SECRET_SCAN_SEVERITY_HINT = "hint"

SECRET_SCAN_TEXT_SUFFIXES = (
    ".bat",
    ".cfg",
    ".cmd",
    ".env",
    ".ini",
    ".json",
    ".md",
    ".ps1",
    ".py",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
)

SECRET_SCAN_EXCLUDED_DIR_NAMES = (
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "node_modules",
)

SENSITIVE_FILENAME_HINTS = (
    ".env",
    ".pem",
    ".key",
    ".p12",
    ".pfx",
)


@dataclass(frozen=True)
class SecretPattern:
    """One regex pattern used by the report-only secret scan gate."""

    name: str
    pattern_text: str
    severity: str

    def compile(self) -> re.Pattern[str]:
        """Compile and return the regex pattern."""
        return re.compile(self.pattern_text, re.IGNORECASE)


SECRET_SCAN_PATTERNS = (
    SecretPattern(
        name="private_key_block",
        pattern_text=r"-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----",
        severity=SECRET_SCAN_SEVERITY_HIGH,
    ),
    SecretPattern(
        name="github_token",
        pattern_text=r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b",
        severity=SECRET_SCAN_SEVERITY_HIGH,
    ),
    SecretPattern(
        name="aws_access_key_id",
        pattern_text=r"\bAKIA[0-9A-Z]{16}\b",
        severity=SECRET_SCAN_SEVERITY_HIGH,
    ),
    SecretPattern(
        name="openai_style_secret_key",
        pattern_text=r"\bsk-[A-Za-z0-9][A-Za-z0-9_-]{20,}\b",
        severity=SECRET_SCAN_SEVERITY_HIGH,
    ),
    SecretPattern(
        name="credential_assignment",
        pattern_text=(
            r"\b(api[_-]?key|secret|token|password|credential)\b"
            r"\s*[:=]\s*['\"]?[^'\"\s]{12,}"
        ),
        severity=SECRET_SCAN_SEVERITY_MEDIUM,
    ),
)


@dataclass(frozen=True)
class SecretScanFinding:
    """One redacted sensitive-value finding."""

    relative_path: str
    line_number: int
    pattern_name: str
    severity: str
    redacted_preview: str
    recommended_action: str


@dataclass(frozen=True)
class SecretScanReport:
    """Report generated by the report-only secret scan gate."""

    source_root: str
    action: str = SECRET_SCAN_ACTION
    findings: tuple[SecretScanFinding, ...] = field(default_factory=tuple)

    @property
    def total_findings(self) -> int:
        """Return the number of findings."""
        return len(self.findings)

    @property
    def high_confidence_findings(self) -> int:
        """Return the number of high-severity findings."""
        return sum(
            1
            for finding in self.findings
            if finding.severity == SECRET_SCAN_SEVERITY_HIGH
        )

    @property
    def medium_confidence_findings(self) -> int:
        """Return the number of medium-severity findings."""
        return sum(
            1
            for finding in self.findings
            if finding.severity == SECRET_SCAN_SEVERITY_MEDIUM
        )

    @property
    def hint_findings(self) -> int:
        """Return the number of file-name hint findings."""
        return sum(
            1
            for finding in self.findings
            if finding.severity == SECRET_SCAN_SEVERITY_HINT
        )

    def is_clean(self) -> bool:
        """Return True when no sensitive values were found."""
        return self.total_findings == 0

    def summary_lines(self) -> list[str]:
        """Return a redacted human-readable summary as lines."""
        lines = [
            "Kanda Reasoner secret scan report",
            f"Action: {self.action}",
            f"Source root: {self.source_root}",
            f"Findings: {self.total_findings}",
            f"High confidence: {self.high_confidence_findings}",
            f"Medium confidence: {self.medium_confidence_findings}",
            f"Hints: {self.hint_findings}",
        ]

        if self.findings:
            lines.append("Findings:")
            for finding in self.findings:
                lines.append(
                    f"  - {finding.relative_path}:{finding.line_number} "
                    f"[{finding.severity}:{finding.pattern_name}] "
                    f"{finding.redacted_preview} -> "
                    f"{finding.recommended_action}"
                )

        return lines

    def summary(self) -> str:
        """Return a redacted human-readable summary."""
        return "\n".join(self.summary_lines())


def _normalize_relative_path(path: Path) -> str:
    """Return a POSIX-style relative path string."""
    return path.as_posix()


def _should_skip_path(path: Path) -> bool:
    """Return True when path is inside a scanner-excluded folder."""
    return any(part in SECRET_SCAN_EXCLUDED_DIR_NAMES for part in path.parts)


def _is_text_candidate(path: Path) -> bool:
    """Return True when the file should be scanned as text."""
    if path.name.lower() == ".env":
        return True
    return path.suffix.lower() in SECRET_SCAN_TEXT_SUFFIXES


def _has_sensitive_filename_hint(path: Path) -> bool:
    """Return True when the file name itself suggests sensitive content."""
    lower_name = path.name.lower()
    if lower_name == ".env":
        return True
    return lower_name.endswith(SENSITIVE_FILENAME_HINTS)


def _redacted_preview(line: str, start: int, end: int) -> str:
    """Return a short preview with the matched sensitive value redacted."""
    clean_line = line.strip().replace("\t", " ")
    prefix = clean_line[: max(start, 0)]
    suffix = clean_line[min(end, len(clean_line)) :]
    preview = (prefix + "<redacted>" + suffix).strip()
    if len(preview) > 120:
        preview = preview[:117] + "..."
    return preview or "<redacted>"


def _make_finding(
    relative_path: str,
    line_number: int,
    pattern_name: str,
    severity: str,
    redacted_preview: str,
) -> SecretScanFinding:
    """Build one redacted finding."""
    return SecretScanFinding(
        relative_path=relative_path,
        line_number=line_number,
        pattern_name=pattern_name,
        severity=severity,
        redacted_preview=redacted_preview,
        recommended_action=(
            "review manually, rotate credential if real, and move secret "
            "to environment, OS credential store, or ignored local config"
        ),
    )


def scan_text_for_secrets(
    relative_path: str,
    text: str,
    patterns: tuple[SecretPattern, ...] = SECRET_SCAN_PATTERNS,
) -> tuple[SecretScanFinding, ...]:
    """Scan supplied text and return redacted findings.

    The returned findings never include the raw matched value.
    """
    findings: list[SecretScanFinding] = []
    compiled_patterns = tuple((item, item.compile()) for item in patterns)

    for line_number, line in enumerate(text.splitlines(), start=1):
        for pattern, compiled in compiled_patterns:
            match = compiled.search(line)
            if match is None:
                continue
            findings.append(
                _make_finding(
                    relative_path=relative_path,
                    line_number=line_number,
                    pattern_name=pattern.name,
                    severity=pattern.severity,
                    redacted_preview=_redacted_preview(
                        line,
                        match.start(),
                        match.end(),
                    ),
                )
            )
            break

    return tuple(findings)


def scan_path_for_secrets(source_root: str | Path) -> SecretScanReport:
    """Scan source_root for likely secrets and return a report-only result.

    The scan never moves, deletes, creates, or modifies files. Values are
    redacted in the returned summary and findings.
    """
    root = normalize_path(source_root)
    if not root.exists() or not root.is_dir():
        raise ValueError(f"source_root must be an existing directory: {root}")

    findings: list[SecretScanFinding] = []

    for item in sorted(root.rglob("*"), key=lambda path: path.as_posix()):
        if _should_skip_path(item.relative_to(root)):
            continue
        if not item.is_file():
            continue

        relative_path = _normalize_relative_path(item.relative_to(root))

        if _has_sensitive_filename_hint(item):
            findings.append(
                _make_finding(
                    relative_path=relative_path,
                    line_number=0,
                    pattern_name="sensitive_filename_hint",
                    severity=SECRET_SCAN_SEVERITY_HINT,
                    redacted_preview="<filename suggests sensitive content>",
                )
            )

        if not _is_text_candidate(item):
            continue

        try:
            text = item.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        findings.extend(scan_text_for_secrets(relative_path, text))

    return SecretScanReport(source_root=str(root), findings=tuple(findings))


def summarize_secret_scan(report: SecretScanReport) -> str:
    """Return a redacted human-readable secret scan summary."""
    return report.summary()


__all__ = [
    "SECRET_SCAN_ACTION",
    "SECRET_SCAN_EXCLUDED_DIR_NAMES",
    "SECRET_SCAN_PATTERNS",
    "SECRET_SCAN_SEVERITY_HIGH",
    "SECRET_SCAN_SEVERITY_HINT",
    "SECRET_SCAN_SEVERITY_MEDIUM",
    "SECRET_SCAN_TEXT_SUFFIXES",
    "SENSITIVE_FILENAME_HINTS",
    "SecretPattern",
    "SecretScanFinding",
    "SecretScanReport",
    "scan_path_for_secrets",
    "scan_text_for_secrets",
    "summarize_secret_scan",
]
