"""Source-cleanliness validator for Kanda Reasoner storage policy.

This module reports non-compilation debris in a source tree. It is report-only:
importing or calling scan functions must not move files, delete files, create
folders, or modify the project. Explicit callers may later use the report to
plan cleanup or migration.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path

from kanda_reasoner_app.storage_policy.build_policy_baseline import (
    DEVELOPMENT_ONLY_WARN_PATTERNS,
    FAIL_BEFORE_COMPILATION_PATTERNS,
    GENERATED_INTENTIONAL_SOURCE_ALLOWLIST,
)
from kanda_reasoner_app.storage_policy.path_resolver import normalize_path

SOURCE_CLEANLINESS_ACTION = "report_only"
SOURCE_CLEANLINESS_CATEGORY_FAILURE = "failure"
SOURCE_CLEANLINESS_CATEGORY_WARNING = "warning"


@dataclass(frozen=True)
class SourceCleanlinessFinding:
    """One source-cleanliness finding."""

    relative_path: str
    pattern: str
    category: str
    is_directory: bool
    recommended_action: str


@dataclass(frozen=True)
class SourceCleanlinessReport:
    """Report generated by source-cleanliness scanning."""

    source_root: str
    action: str = SOURCE_CLEANLINESS_ACTION
    failures: tuple[SourceCleanlinessFinding, ...] = field(default_factory=tuple)
    warnings: tuple[SourceCleanlinessFinding, ...] = field(default_factory=tuple)

    @property
    def total_failures(self) -> int:
        """Return the number of failure findings."""
        return len(self.failures)

    @property
    def total_warnings(self) -> int:
        """Return the number of warning findings."""
        return len(self.warnings)

    @property
    def total_findings(self) -> int:
        """Return the total number of findings."""
        return self.total_failures + self.total_warnings

    def is_clean(self) -> bool:
        """Return True when there are no failures and no warnings."""
        return self.total_findings == 0

    def is_compilation_clean(self) -> bool:
        """Return True when there are no compilation-blocking failures."""
        return self.total_failures == 0

    def summary_lines(self) -> list[str]:
        """Return a human-readable report summary as lines."""
        lines = [
            "Kanda Reasoner source cleanliness report",
            f"Action: {self.action}",
            f"Source root: {self.source_root}",
            f"Failures: {self.total_failures}",
            f"Warnings: {self.total_warnings}",
        ]

        if self.failures:
            lines.append("Failure findings:")
            for finding in self.failures:
                lines.append(
                    f"  - {finding.relative_path} "
                    f"[{finding.pattern}] -> {finding.recommended_action}"
                )

        if self.warnings:
            lines.append("Warning findings:")
            for finding in self.warnings:
                lines.append(
                    f"  - {finding.relative_path} "
                    f"[{finding.pattern}] -> {finding.recommended_action}"
                )

        return lines

    def summary(self) -> str:
        """Return a human-readable report summary."""
        return "\n".join(self.summary_lines())


def _normalize_relative_path(relative_path: Path, is_directory: bool) -> str:
    """Return a normalized POSIX-style relative path for matching."""
    value = relative_path.as_posix()
    if value == ".":
        value = relative_path.name
    if is_directory:
        return value.rstrip("/") + "/"
    return value


def _pattern_matches(path_text: str, pattern: str) -> bool:
    """Return True when a policy pattern matches a normalized path."""
    normalized_pattern = pattern.replace("\\", "/")
    normalized_path = path_text.replace("\\", "/")

    if normalized_pattern.endswith("/"):
        bare_pattern = normalized_pattern.rstrip("/")
        bare_path = normalized_path.rstrip("/")
        return bare_path == bare_pattern or fnmatch(bare_path, bare_pattern)

    return fnmatch(normalized_path.rstrip("/"), normalized_pattern)


def _first_matching_pattern(
    path_text: str,
    patterns: tuple[str, ...],
) -> str | None:
    """Return the first matching pattern, or None."""
    for pattern in patterns:
        if _pattern_matches(path_text, pattern):
            return pattern
    return None


def _is_allowlisted_source(path_text: str) -> bool:
    """Return True when path is declared generated-intentional source."""
    normalized_path = path_text.rstrip("/")
    for allowed in GENERATED_INTENTIONAL_SOURCE_ALLOWLIST:
        if normalized_path == allowed or normalized_path.endswith("/" + allowed):
            return True
    return False


def _make_failure(relative_path: str, pattern: str, is_directory: bool) -> SourceCleanlinessFinding:
    """Build a compilation-blocking source-cleanliness finding."""
    return SourceCleanlinessFinding(
        relative_path=relative_path,
        pattern=pattern,
        category=SOURCE_CLEANLINESS_CATEGORY_FAILURE,
        is_directory=is_directory,
        recommended_action=(
            "move to Kanda maintenance root, migrate evidence, or remove "
            "only after review"
        ),
    )


def _make_warning(relative_path: str, pattern: str, is_directory: bool) -> SourceCleanlinessFinding:
    """Build a development-only warning finding."""
    return SourceCleanlinessFinding(
        relative_path=relative_path,
        pattern=pattern,
        category=SOURCE_CLEANLINESS_CATEGORY_WARNING,
        is_directory=is_directory,
        recommended_action="exclude from packaged builds or review before release",
    )


def scan_source_cleanliness(
    source_root: str | Path,
    fail_patterns: tuple[str, ...] = FAIL_BEFORE_COMPILATION_PATTERNS,
    warning_patterns: tuple[str, ...] = DEVELOPMENT_ONLY_WARN_PATTERNS,
) -> SourceCleanlinessReport:
    """Scan source_root and return a report-only source-cleanliness report.

    The scan never moves, deletes, creates, or modifies files.
    """
    root = normalize_path(source_root)
    if not root.exists() or not root.is_dir():
        raise ValueError(f"source_root must be an existing directory: {root}")

    failures: list[SourceCleanlinessFinding] = []
    warnings: list[SourceCleanlinessFinding] = []

    for item in sorted(root.rglob("*"), key=lambda path: path.as_posix()):
        relative_path = _normalize_relative_path(
            item.relative_to(root),
            is_directory=item.is_dir(),
        )

        if _is_allowlisted_source(relative_path):
            continue

        failure_pattern = _first_matching_pattern(relative_path, fail_patterns)
        if failure_pattern is not None:
            failures.append(
                _make_failure(
                    relative_path,
                    failure_pattern,
                    is_directory=item.is_dir(),
                )
            )
            continue

        warning_pattern = _first_matching_pattern(relative_path, warning_patterns)
        if warning_pattern is not None:
            warnings.append(
                _make_warning(
                    relative_path,
                    warning_pattern,
                    is_directory=item.is_dir(),
                )
            )

    return SourceCleanlinessReport(
        source_root=str(root),
        failures=tuple(failures),
        warnings=tuple(warnings),
    )


def summarize_source_cleanliness(report: SourceCleanlinessReport) -> str:
    """Return a human-readable source-cleanliness summary."""
    return report.summary()


__all__ = [
    "SOURCE_CLEANLINESS_ACTION",
    "SOURCE_CLEANLINESS_CATEGORY_FAILURE",
    "SOURCE_CLEANLINESS_CATEGORY_WARNING",
    "SourceCleanlinessFinding",
    "SourceCleanlinessReport",
    "scan_source_cleanliness",
    "summarize_source_cleanliness",
]
